import { DuaItem } from '../types';

export const ISLAMIC_TRAVEL_DUAS: DuaItem[] = [
  {
    id: 'dua-1',
    category: 'Boarding Transport',
    title: 'Dua When Boarding or Mounting Transport (വാഹനത്തിൽ കയറുമ്പോൾ)',
    arabic: 'سُبْحَانَ الَّذِي سَخَّرَ لَنَا هَذَا وَمَا كُنَّا لَهُ مُقْرِنِينَ ، وَإِنَّا إِلَى رَبِّنَا لَمُنْقَلِبُونَ',
    transliteration:
      'Subhanal-ladhee sakh-khara lana hadha wa ma kunna lahu muqrinin, wa inna ila Rabbina lamunqaliboon.',
    english:
      'Glory is to Him Who has subjected this to us, and we were not able by ourselves to subdue it. And surely, unto our Lord we will return.',
    malayalam:
      'ഞങ്ങൾക്ക് ഇത് അധീനപ്പെടുത്തിത്തന്നവൻ എത്രയോ പരിശുദ്ധൻ! ഞങ്ങൾക്കിതിന് സ്വന്തമായി കഴിവുണ്ടായിരുന്നില്ല. തീർച്ചയായും നാം നമ്മുടെ രക്ഷിതാവിലേക്ക് മടങ്ങുന്നവരാകുന്നു.',
    reference: "Qur'an (Surah Az-Zukhruf 43:13-14) & Sahih Muslim 1342",
    context: 'Recite when boarding your flight, train, bus, ship, or car.',
  },
  {
    id: 'dua-2',
    category: 'Before Journey',
    title: 'Dua for the Entire Journey (യാത്രാ ആരംഭത്തിലെ സമഗ്ര ദുആ)',
    arabic:
      'اللَّهُمَّ إِنَّا نَسْأَلُكَ فِي سَفَرِنَا هَذَا الْبِرَّ وَالتَّقْوَى، وَمِنَ الْعَمَلِ مَا تَرْضَى، اللَّهُمَّ هَوِّنْ عَلَيْنَا سَفَرَنَا هَذَا، وَاطْوِ عَنَّا بُعْدَهُ، اللَّهُمَّ أَنْتَ الصَّاحِبُ فِي السَّفَرِ، وَالْخَلِيفَةُ فِي الأَهْلِ ، اللَّهُمَّ إِنِّي أَعُوذُ بِكَ مِنْ وَعْثَاءِ السَّفَرِ ، وَكَآبَةِ الْمَنْظَرِ ، وَسُوءِ الْمُنْقَلَبِ فِي الْمَالِ وَالأَهْلِ',
    transliteration:
      'Allahumma inna nas\'aluka fee safarina hadha al-birra wat-taqwa, wa minal-\'amali ma tarda. Allahumma hawwin \'alayna safarana hadha, watwi \'anna bu\'dah. Allahumma Antas-Sahibu fis-safar, wal-Khaleefatu fil-ahl. Allahumma inni a\'oodhu bika min wa\'tha\'is-safar, wa ka\'abatil-manzar, wa soo\'il-munqalabi fil-mali wal-ahl.',
    english:
      'O Allah, we ask You on this journey for goodness, piety, and deeds that please You. O Allah, make this journey easy for us and shorten its distance. O Allah, You are our Companion in travel and the Protector of our family. O Allah, I seek refuge in You from the hardships of travel, distressing sights, and an unfortunate return concerning wealth and family.',
    malayalam:
      'അല്ലാഹുവേ! ഞങ്ങളുടെ ഈ യാത്രയിൽ നന്മയും തഖ്‌വയും നീ തൃപ്തിപ്പെടുന്ന പ്രവർത്തനങ്ങളും ഞങ്ങൾ നിന്നോട് അപേക്ഷിക്കുന്നു. അല്ലാഹുവേ, ഞങ്ങൾക്ക് ഈ യാത്ര എളുപ്പമാക്കേണമേ, ഇതിന്റെ ദൂരം ചുരുക്കേണമേ. അല്ലാഹുവേ, യാത്രയിലെ ചങ്ങാതിയും വീട്ടുകാരുടെ സംരക്ഷകനും നീയാകുന്നു. യാത്രയുടെ പ്രയാസങ്ങളിൽ നിന്നും ദുഃഖകരമായ കാഴ്ചകളിൽ നിന്നും സമ്പത്തിലും കുടുംബത്തിലും ഉണ്ടാകുന്ന ദോഷകരമായ മാറ്റങ്ങളിൽ നിന്നും ഞാൻ നിന്നിൽ അഭയം തേടുന്നു.',
    reference: 'Sahih Muslim 1342 (Kitab al-Hajj)',
    context: 'Recited by the Prophet (ﷺ) upon commencing a journey.',
  },
  {
    id: 'dua-leaving-home',
    category: 'Before Journey',
    title: 'Dua When Stepping Out of the House (വീട്ടിൽ നിന്ന് ഇറങ്ങുമ്പോൾ)',
    arabic: 'بِسْمِ اللَّهِ ، تَوَكَّلْتُ عَلَى اللَّهِ ، وَلَا حَوْلَ وَلَا قُوَّةَ إِلَّا بِاللَّهِ',
    transliteration: 'Bismillahi, tawakkaltu \'alallahi, wa la hawla wa la quwwata illa billah.',
    english: 'In the name of Allah, I place my trust in Allah, and there is no might nor power except with Allah.',
    malayalam: 'അല്ലാഹുവിന്റെ നാമത്തിൽ, ഞാൻ അല്ലാഹുവിൽ ഭരമേൽപ്പിച്ചിരിക്കുന്നു; അല്ലാഹുവെക്കൊണ്ടല്ലാതെ യാതൊരു ഉപായവുമില്ല, യാതൊരു ശക്തിയുമില്ല.',
    reference: 'Sunan Abi Dawud 5095, Jami` at-Tirmidhi 3426 (Sahih)',
    context: 'Recited upon stepping out of your front door to begin your voyage. Angels respond: "You are guided, protected, and defended."',
  },
  {
    id: 'dua-uphill-downhill',
    category: 'En Route',
    title: 'Takbeer When Ascending & Tasbeeh When Descending (കയറ്റത്തിലും ഇറക്കത്തിലും)',
    arabic: 'اللَّهُ أَكْبَرُ (عِنْدَ الصُّعُودِ) • سُبْحَانَ اللَّهِ (عِنْدَ النُّزُولِ)',
    transliteration: 'Allahu Akbar (When going uphill/takeoff) • Subhanallah (When going downhill/landing)',
    english: 'Say "Allahu Akbar" (Allah is the Greatest) when ascending hills, flyovers, or taking off in flight. Say "Subhanallah" (Glory be to Allah) when descending slopes, valleys, or landing.',
    malayalam: 'കയറ്റങ്ങൾ കയറുമ്പോഴും വിമാനം ടേക്ക് ഓഫ് ചെയ്യുമ്പോഴും "അല്ലാഹു അക്ബർ" എന്ന് പറയുക. ഇറക്കങ്ങൾ ഇറങ്ങുമ്പോഴും വിമാനം ലാൻഡ് ചെയ്യുമ്പോഴും "സുബ്ഹാനല്ലാഹ്" എന്ന് പറയുക.',
    reference: 'Sahih al-Bukhari 2993, Sunan Abi Dawud 2599',
    context: 'Sunnah of Jabir ibn Abdullah (RA) and the Sahabah during all travel journeys.',
  },
  {
    id: 'dua-hotel-rest-stop',
    category: 'En Route',
    title: 'Dua When Halting at a Hotel, Station, or Rest Stop (ഹോട്ടലിലോ തങ്ങുന്ന സ്ഥലത്തോ എത്തുമ്പോൾ)',
    arabic: 'أَعُوذُ بِكَلِمَاتِ اللَّهِ التَّامَّاتِ مِنْ شَرِّ مَا خَلَقَ',
    transliteration: 'A\'oodhu bi-kalimatillahit-tammati min sharri ma khalaq.',
    english: 'I seek refuge in the perfect words of Allah from the evil of that which He has created.',
    malayalam: 'അല്ലാഹു സൃഷ്ടിച്ച സർവ്വ സൃഷ്ടികളുടെയും തിന്മകളിൽ നിന്ന് അവന്റെ പരിപൂർണ്ണമായ വചനങ്ങൾ കൊണ്ട് ഞാൻ കാവൽ തേടുന്നു.',
    reference: 'Sahih Muslim 2708',
    context: 'Recite when checking into a hotel room, airport lounge, campsite, or highway rest stop. Hadith: "Nothing will harm him until he departs from that place."',
  },
  {
    id: 'dua-fear-turbulence',
    category: 'En Route',
    title: 'Dua During Flight Turbulence, Fear, or Difficulty (വിമാന കുലുക്കമോ ഭയമോ ഉണ്ടാകുമ്പോൾ)',
    arabic: 'اللَّهُمَّ إِنَّا نَجْعَلُكَ فِي نُحُورِهِمْ وَنَعُوذُ بِكَ مِنْ شُرُورِهِمْ ، حَسْبُنَا اللَّهُ وَنِعْمَ الْوَكِيلُ',
    transliteration: 'Allahumma inna naj\'aluka fee nuhoorihim wa na\'oodhu bika min shuroorihim. Hasbunallahu wa ni\'mal-Wakeel.',
    english: 'O Allah, we place You before them and seek refuge in You from their wickedness. Allah is sufficient for us, and He is the best Disposer of affairs.',
    malayalam: 'അല്ലാഹുവേ! ഞങ്ങൾ നിന്നെ അവരുടെ നേരെ മുൻനിർത്തുകയും അവരുടെ ദ്രോഹങ്ങളിൽ നിന്ന് നിന്നിൽ കാവൽ തേടുകയും ചെയ്യുന്നു. അല്ലാഹു ഞങ്ങൾക്ക് മതിയായവനാണ്; അവൻ ഭരമേൽപ്പിക്കാൻ എത്രയോ ഉത്തമൻ.',
    reference: 'Sunan Abi Dawud 1537, Sahih al-Bukhari 4563',
    context: 'Recite in severe turbulence, unexpected travel delays, border scrutiny, or fearful situations.',
  },
  {
    id: 'dua-3',
    category: 'Entering a City',
    title: 'Dua When Entering a New Town, City, or Destination (പുതിയ നാട്ടിൽ പ്രവേശിക്കുമ്പോൾ)',
    arabic:
      'اللَّهُمَّ رَبَّ السَّمَاوَاتِ السَّبْعِ وَمَا أَظْلَلْنَ ، وَرَبَّ الْأَرَضِينَ السَّبْعِ وَمَا أَقْلَلْنَ ، وَرَبَّ الشَّيَاطِينِ وَمَا أَضْلَلْنَ ، وَرَبَّ الرِّيَاحِ وَمَا ذَرَيْنَ ، أَسْأَلُكَ خَيْرَ هَذِهِ الْقَرْيَةِ وَخَيْرَ أَهْلِهَا وَخَيْرَ مَا فِيهَا ، وَأَعُوذُ بِكَ مِنْ شَرِّهَا وَشَرِّ أَهْلِهَا وَشَرِّ مَا فِيهَا',
    transliteration:
      'Allahumma Rabbas-samawatis-sab\'i wa ma azlalna, wa Rabbal-ardeenas-sab\'i wa ma aqlalna, wa Rabbash-shayaateeni wa ma adlalna, wa Rabbar-riyahi wa ma dharayna, as\'aluka khayra hadhihil-qaryati wa khayra ahliha wa khayra ma feeha, wa a\'oodhu bika min sharriha wa sharri ahliha wa sharri ma feeha.',
    english:
      'O Allah, Lord of the seven heavens and all they overshadow, Lord of the seven earths and all they carry, Lord of the devils and all they mislead, Lord of the winds and all they blow! I ask You for the good of this town, the good of its people, and the good of what is in it. And I seek refuge in You from its evil, the evil of its people, and the evil of what is in it.',
    malayalam:
      'ഏഴു ആകാശങ്ങളുടെയും അവ തണലിട്ടവയുടെയും രക്ഷിതാവേ, ഏഴു ഭൂമികളുടെയും അവ വഹിച്ചവയുടെയും രക്ഷിതാവേ, പിശാചുക്കളുടെയും അവ വഴിതെറ്റിച്ചവയുടെയും രക്ഷിതാവേ! ഈ നാടിന്റെയും ഇവിടത്തെ ജനങ്ങളുടെയും ഇതിലുള്ള എല്ലാറ്റിന്റെയും നന്മ ഞാൻ നിന്നോട് ചോദിക്കുന്നു. ഇതിന്റെയും ഇവിടത്തെ ജനങ്ങളുടെയും ഇതിലുള്ള എല്ലാറ്റിന്റെയും തിന്മയിൽ നിന്ന് ഞാൻ നിന്നിൽ അഭയം തേടുന്നു.',
    reference: 'Al-Hakim (2/100, Sahih by Dhahabi), Ibn Hibban & Sunan An-Nasa\'i al-Kubra 8816',
    context: 'Recite when your plane touches down, entering the city limits, or seeing your destination from afar.',
  },
  {
    id: 'dua-5',
    category: 'Farewell & Family',
    title: 'Farewell Supplication for the Traveler (യാത്രക്കാരനോട് വിടപറയുമ്പോൾ)',
    arabic: 'أَسْتَوْدِعُ اللَّهَ دِينَكَ، وَأَمَانَتَكَ، وَخَوَاتِيمَ عَمَلِكَ',
    transliteration: "Astawdi'ullaha deenaka, wa amanataka, wa khawateema 'amalika.",
    english: 'I entrust to Allah your religion, your trust, and the final outcomes of your deeds.',
    malayalam: 'താങ്കളുടെ ദീനും, അമാനത്തും, പ്രവർത്തനങ്ങളുടെ അന്ത്യവും ഞാൻ അല്ലാഹുവിങ്കൽ ഭരമേൽപ്പിക്കുന്നു.',
    reference: 'Jami` at-Tirmidhi 3443, Abu Dawood 2600 (Sahih)',
    context: 'Recite when bidding farewell to departing family members or travel companions.',
  },
  {
    id: 'dua-family-left-behind',
    category: 'Farewell & Family',
    title: 'Traveler\'s Dua for the Family Left Behind (വീട്ടുകാരോട് യാത്രപറയുമ്പോൾ)',
    arabic: 'أَسْتَوْدِعُكُمُ اللَّهَ الَّذِي لَا تَضِيعُ وَدَائِعُهُ',
    transliteration: 'Astawdi\'ukumullahal-ladhee la tadee\'u wada\'i\'uh.',
    english: 'I entrust you to Allah, Whose trusts and deposits are never lost or neglected.',
    malayalam: 'തന്റെ അടുക്കൽ ഭരമേൽപ്പിക്കപ്പെട്ടത് നഷ്ടപ്പെട്ടുപോകാത്ത അല്ലാഹുവിങ്കൽ ഞാൻ നിങ്ങളെ ഭരമേൽപ്പിക്കുന്നു.',
    reference: 'Sunan Ibn Majah 2825, Musnad Ahmad (Sahih)',
    context: 'Recite to your spouse, children, and parents before stepping out on journey.',
  },
  {
    id: 'dua-4',
    category: 'Returning Home',
    title: 'Dua When Returning from Travel (യാത്ര കഴിഞ്ഞ് തിരിച്ചെത്തുമ്പോൾ)',
    arabic: 'آيِبُونَ تَائِبُونَ عَابِدُونَ لِرَبِّنَا حَامِدُونَ',
    transliteration: 'Ayiboona, ta\'iboona, \'abidoona, li-Rabbina hamidoon.',
    english: 'We are returning, repenting, worshipping, and praising our Lord.',
    malayalam: 'ഞങ്ങൾ മടങ്ങുന്നവരും, പശ്ചാത്തപിക്കുന്നവരും, ഇബാദത്ത് ചെയ്യുന്നവരും, ഞങ്ങളുടെ രക്ഷിതാവിനെ സ്തുതിക്കുന്നവരുമാകുന്നു.',
    reference: 'Sahih al-Bukhari 1799, Sahih Muslim 1342',
    context: 'Recite upon your return journey heading back and upon entering your home town.',
  },
  {
    id: 'dua-entering-home-return',
    category: 'Returning Home',
    title: 'Dua When Entering Home After Voyage (യാത്ര കഴിഞ്ഞ് വീട്ടിൽ കയറുമ്പോൾ)',
    arabic: 'تَوْبًا تَوْبًا لِرَبِّنَا أَوْبًا لَا يُغَادِرُ حَوْبًا',
    transliteration: 'Tawban tawban, li-Rabbina awban, la yughadiru hawba.',
    english: 'Repentance, repentance, returning to our Lord, leaving behind no sin or burden.',
    malayalam: 'പശ്ചാത്താപം! പശ്ചാത്താപം! ഞങ്ങളുടെ രക്ഷിതാവിങ്കലേക്ക് ഒരു മടക്കം, യാതൊരു പാപവും ബാക്കിവെക്കാത്ത വിധം.',
    reference: 'Musnad Ahmad 2111, Al-Hakim (Sahih)',
    context: 'Recite when crossing the threshold of your home upon returning from travel.',
  },
  {
    id: 'dua-lost-way',
    category: 'En Route',
    title: 'Dua When Losing the Way or Navigation (വഴി തെറ്റുമ്പോഴോ നഷ്ടപ്പെടുമ്പോഴോ)',
    arabic: 'يَا هَادِيَ الضَّالَّةِ وَرَادَّ الضَّالَّةِ ارْدُدْ عَلَيَّ ضَالَّتِي بِعِزَّتِكَ وَسُلْطَانِكَ فَإِنَّهَا مِنْ عَطَائِكَ وَفَضْلِكَ',
    transliteration: 'Ya Hadiyad-dallati wa raddad-dallati urdud \'alayya dallati bi-\'izzatika wa sultanika fa-innaha min \'ata\'ika wa fadlik.',
    english: 'O Guide of the lost and Restorer of the stray, restore to me that which I have lost by Your Might and Authority, for it is from Your gift and bounty.',
    malayalam: 'വഴിതെറ്റിയവർക്ക് മാർഗ്ഗദർശനം നൽകുന്നവനേ, നഷ്ടപ്പെട്ടത് തിരിച്ചു നൽകുന്നവനേ! നിന്റെ പ്രതാപം കൊണ്ട് എനിക്ക് വഴി കാണിച്ചു തരേണമേ.',
    reference: 'Al-Bayhaqi in Shu\'ab al-Iman, classical Shafi\'i Adhkar',
    context: 'Recite when lost in a foreign city, missing transit connections, or misplaced luggage.',
  }
];
