import { Place } from '../types';

export const INITIAL_PLACES: Place[] = [
  // ==========================================
  // KERALA HISTORIC MOSQUES & PALLIS (പള്ളികൾ)
  // ==========================================
  {
    id: 'mosque-kerala-1',
    name: 'Cheraman Juma Masjid',
    city: 'Kodungallur (Thrissur)',
    country: 'India',
    category: 'mosque',
    rating: 4.9,
    reviewsCount: 14200,
    distance: '38 km from Kochi',
    address: 'Paravur - Kodungallur Rd, Padakulam, Kodungallur, Kerala 680664',
    lat: 10.2155,
    lng: 76.2003,
    image: 'https://images.unsplash.com/photo-1590076215667-875d4ef2d7ee?auto=format&fit=crop&w=800&q=80',
    openNow: true,
    openingHours: 'Open 24/7 for Salah & Visitors',
    facilities: [
      'Built in 629 CE (India\'s Oldest Mosque, built during Prophet\'s ﷺ era)',
      'Historic 1400-Year Ancient Brass Oil Lamp (Vilakku)',
      'Cheraman Islamic Heritage Museum & Library',
      'Spacious Traditional Ablution Pond & Running Wudu Taps',
      'Dedicated Women\'s Prayer Section with Air-conditioning',
    ],
    hasWomensArea: true,
    hasWuduArea: true,
    hasWheelchairAccess: true,
    jumuaTime: '12:45 PM (Khutbah with Malayalam guidance)',
  },
  {
    id: 'mosque-kerala-2',
    name: 'Mishkal Mosque (Mishkal Palli)',
    city: 'Kozhikode (Calicut)',
    country: 'India',
    category: 'mosque',
    rating: 4.9,
    reviewsCount: 9850,
    distance: '1.2 km from Kozhikode Beach',
    address: 'Kuttichira, Kozhikode, Kerala 673001',
    lat: 11.2435,
    lng: 75.7766,
    image: 'https://images.unsplash.com/photo-1542601906990-b4d3fb778b09?auto=format&fit=crop&w=800&q=80',
    openNow: true,
    openingHours: '04:30 AM - 10:00 PM',
    facilities: [
      '14th-Century Four-Tiered Wooden Gabled Architecture',
      'Historic Kuttichira Ablution Pond (Kulam)',
      'Arab-Malabar Maritime Heritage & Zamorin Ally',
      'Dedicated Women\'s Prayer Wing',
      '5 Daily Congregational Prayers with Shafi\'i Qunut',
    ],
    hasWomensArea: true,
    hasWuduArea: true,
    hasWheelchairAccess: false,
    jumuaTime: '01:00 PM (Friday Jumu\'ah with Malayalam Bayan)',
  },
  {
    id: 'mosque-kerala-3',
    name: 'Ponnani Valiya Juma Masjid',
    city: 'Ponnani (Malappuram)',
    country: 'India',
    category: 'mosque',
    rating: 4.9,
    reviewsCount: 8940,
    distance: 'Heart of Historic Ponnani Port',
    address: 'Halve Street, Ponnani, Malappuram, Kerala 679577',
    lat: 10.7672,
    lng: 75.925,
    image: 'https://images.unsplash.com/photo-1564507592333-c60657eea523?auto=format&fit=crop&w=800&q=80',
    openNow: true,
    openingHours: 'Open 24/7 for Congregations',
    facilities: [
      'Built in 1519 CE by Sheikh Zaynuddin Makhdum I',
      'Historical "Little Makkah" of Malabar & Seminary of Fath al-Mu\'in',
      'Ancient "Vilakkilirikkal" Traditional Scholar Circle Lamp',
      'Exquisite Malabar Teak Wood Carvings & Arabic Calligraphy',
      'Spacious Traditional Ablution Pond & Separate Ladies Area',
    ],
    hasWomensArea: true,
    hasWuduArea: true,
    hasWheelchairAccess: true,
    jumuaTime: '12:45 PM',
  },
  {
    id: 'mosque-kerala-4',
    name: 'Mannarkkad Valiya Juma Masjid',
    city: 'Mannarkkad (Palakkad)',
    country: 'India',
    category: 'mosque',
    rating: 4.8,
    reviewsCount: 5210,
    distance: 'Mannarkkad Town Center',
    address: 'Main Road, Mannarkkad, Palakkad District, Kerala 678582',
    lat: 10.9888,
    lng: 76.4608,
    image: 'https://images.unsplash.com/photo-1584551246679-0daf3d275d0f?auto=format&fit=crop&w=800&q=80',
    openNow: true,
    openingHours: '04:30 AM - 10:30 PM',
    facilities: [
      'Central Congregational Mosque of Mannarkkad & Silent Valley Foothills',
      'Air-conditioned Main Prayer Hall',
      'Clean Running Water Ablution Complex',
      'Spacious Women\'s Prayer Section with Separate Gate',
      'Friday Khutbah with Malayalam guidance',
    ],
    hasWomensArea: true,
    hasWuduArea: true,
    hasWheelchairAccess: true,
    jumuaTime: '12:45 PM',
  },
  {
    id: 'mosque-kerala-5',
    name: 'Malik Deenar Great Juma Masjid',
    city: 'Kasaragod',
    country: 'India',
    category: 'mosque',
    rating: 4.9,
    reviewsCount: 11200,
    distance: '3.5 km from Kasaragod Railway Station',
    address: 'Thalangara, Kasaragod, Kerala 671122',
    lat: 12.5102,
    lng: 74.9852,
    image: 'https://images.unsplash.com/photo-1541432901042-2d8bd64b4a9b?auto=format&fit=crop&w=800&q=80',
    openNow: true,
    openingHours: '04:30 AM - 10:30 PM',
    facilities: [
      'Founded by Sahaba Malik ibn Dinar (RA) in 7th Century',
      'Arabian Sea coastal breeze & historic estuary',
      'Grave of Malik ibn Dinar inside the complex',
      'Extensive Heritage Courtyards & Ablution Pool',
      'Large Congregational Capacity for Friday Jumu\'ah',
    ],
    hasWomensArea: true,
    hasWuduArea: true,
    hasWheelchairAccess: true,
    jumuaTime: '01:00 PM',
  },
  {
    id: 'mosque-kerala-6',
    name: 'Muchundi Mosque (Kuttichira)',
    city: 'Kozhikode (Calicut)',
    country: 'India',
    category: 'mosque',
    rating: 4.8,
    reviewsCount: 4620,
    distance: '400 m from Mishkal Mosque',
    address: 'Kuttichira, Kozhikode, Kerala 673001',
    lat: 11.2415,
    lng: 75.7788,
    image: 'https://images.unsplash.com/photo-1564507592333-c60657eea523?auto=format&fit=crop&w=800&q=80',
    openNow: true,
    openingHours: 'Open for 5 Daily Prayers',
    facilities: [
      '13th-Century Stone Decree Gifted by Hindu Zamorin King',
      'Ancient Old Malayalam Vatteluttu Script Inscription',
      'Traditional Gabled Wooden Roof & Intricate Carvings',
      'Serene Kuttichira Community Quarter',
    ],
    hasWomensArea: true,
    hasWuduArea: true,
    hasWheelchairAccess: false,
    jumuaTime: '12:50 PM',
  },
  {
    id: 'mosque-kerala-7',
    name: 'Palayam Juma Masjid (Masjid-i Jahan-Numa)',
    city: 'Thiruvananthapuram',
    country: 'India',
    category: 'mosque',
    rating: 4.8,
    reviewsCount: 7800,
    distance: '500 m from Central Station',
    address: 'Palayam, Thiruvananthapuram, Kerala 695034',
    lat: 8.5028,
    lng: 76.9515,
    image: 'https://images.unsplash.com/photo-1590076215667-875d4ef2d7ee?auto=format&fit=crop&w=800&q=80',
    openNow: true,
    openingHours: 'Open for all 5 daily prayers',
    facilities: [
      'Heart of Capital City Trivandrum beside University & Church',
      'Air-conditioned Main Prayer Hall',
      'Friday Khutbah with Malayalam Translation',
      'Extensive Women\'s Wing with Separate Entry',
      'Wheelchair Ramps & Clean Ablution Block',
    ],
    hasWomensArea: true,
    hasWuduArea: true,
    hasWheelchairAccess: true,
    jumuaTime: '12:45 PM',
  },
  {
    id: 'mosque-kerala-8',
    name: 'Madayi Mosque (Madayi Palli)',
    city: 'Kannur',
    country: 'India',
    category: 'mosque',
    rating: 4.8,
    reviewsCount: 4120,
    distance: 'Pazhayangadi, Kannur',
    address: 'Madayi, Pazhayangadi, Kannur, Kerala 670303',
    lat: 12.0305,
    lng: 75.2589,
    image: 'https://images.unsplash.com/photo-1542601906990-b4d3fb778b09?auto=format&fit=crop&w=800&q=80',
    openNow: true,
    openingHours: '05:00 AM - 09:30 PM',
    facilities: [
      'Historic 12th-century mosque with white marble slab from Makkah',
      'Founded during Malik ibn Dinar\'s expedition',
      'Panoramic scenic hillside location overlooking river',
      'Ablution pond & prayer halls',
    ],
    hasWomensArea: true,
    hasWuduArea: true,
    hasWheelchairAccess: true,
    jumuaTime: '12:45 PM',
  },
  {
    id: 'mosque-kerala-9',
    name: 'Mampuram Maqam & Juma Masjid',
    city: 'Malappuram',
    country: 'India',
    category: 'mosque',
    rating: 4.9,
    reviewsCount: 15400,
    distance: 'Tirurangadi, Malappuram',
    address: 'Mampuram, Tirurangadi, Malappuram, Kerala 676306',
    lat: 11.0425,
    lng: 75.9892,
    image: 'https://images.unsplash.com/photo-1584551246679-0daf3d275d0f?auto=format&fit=crop&w=800&q=80',
    openNow: true,
    openingHours: '04:00 AM - 11:00 PM',
    facilities: [
      'Spiritual sanctuary of Sayyid Alavi Thangal of Hadramawt',
      'Major pilgrimage hub of Malabar Muslims',
      'Vast congregational halls and peaceful riverside courtyard',
      'Extensive wudu facilities & food distribution (Nercha)',
    ],
    hasWomensArea: true,
    hasWuduArea: true,
    hasWheelchairAccess: true,
    jumuaTime: '12:40 PM',
  },
  {
    id: 'mosque-kerala-10',
    name: 'Calvathy Juma Masjid',
    city: 'Kochi (Fort Kochi)',
    country: 'India',
    category: 'mosque',
    rating: 4.8,
    reviewsCount: 3950,
    distance: 'Fort Kochi heritage zone',
    address: 'Calvathy Canal Rd, Fort Kochi, Kochi, Kerala 682001',
    lat: 9.9678,
    lng: 76.2483,
    image: 'https://images.unsplash.com/photo-1564507592333-c60657eea523?auto=format&fit=crop&w=800&q=80',
    openNow: true,
    openingHours: '05:00 AM - 10:00 PM',
    facilities: [
      'Historic maritime mosque on Fort Kochi canal',
      'Rich Arab, Yemeni & Malabar trader legacy',
      'Walking distance to Mattancherry spice markets',
      'Ablution area and serene inner prayer hall',
    ],
    hasWomensArea: true,
    hasWuduArea: true,
    hasWheelchairAccess: false,
    jumuaTime: '12:45 PM',
  },
  {
    id: 'mosque-kerala-11',
    name: 'Vythiri Juma Masjid',
    city: 'Wayanad',
    country: 'India',
    category: 'mosque',
    rating: 4.7,
    reviewsCount: 3100,
    distance: 'Vythiri, Wayanad Hill Station',
    address: 'NH 766, Vythiri, Wayanad, Kerala 673576',
    lat: 11.5511,
    lng: 76.0415,
    image: 'https://images.unsplash.com/photo-1590076215667-875d4ef2d7ee?auto=format&fit=crop&w=800&q=80',
    openNow: true,
    openingHours: '05:00 AM - 10:00 PM',
    facilities: [
      'Scenic Western Ghats mountain tea plantation setting',
      'Warm water ablution facility in cool weather',
      'Ideal traveler stopover along Kozhikode-Bangalore highway',
    ],
    hasWomensArea: true,
    hasWuduArea: true,
    hasWheelchairAccess: true,
    jumuaTime: '12:45 PM',
  },

  // ==========================================
  // KERALA AUTHENTIC HALAL DINING (ഹലാൽ ഭക്ഷണം)
  // ==========================================
  {
    id: 'food-kerala-1',
    name: 'Paragon Restaurant',
    city: 'Kozhikode (Calicut)',
    country: 'India',
    category: 'restaurant',
    rating: 4.9,
    reviewsCount: 38200,
    distance: 'Near Kozhikode Railway Station',
    address: 'Kannur Rd, Near CH Flyover, Kozhikode, Kerala 673004',
    lat: 11.2588,
    lng: 75.7804,
    image: 'https://images.unsplash.com/photo-1589302168068-964664d93dc0?auto=format&fit=crop&w=800&q=80',
    openNow: true,
    openingHours: '06:30 AM - 11:30 PM',
    cuisine: 'Authentic Malabar Biryani, Fish Moilee & Seafood',
    priceRange: '₹₹',
    halalCertification: '100% Halal Verified • No Pork / No Alcohol',
    alcoholFree: true,
    hasPrayerSpace: true,
    popularDishes: ['Kozhikode Chicken Biryani', 'Mutton Dum Biryani', 'Fish Mango Curry', 'Sulaimani Tea'],
  },
  {
    id: 'food-kerala-2',
    name: 'Rahmath Restaurant',
    city: 'Kozhikode (Calicut)',
    country: 'India',
    category: 'restaurant',
    rating: 4.9,
    reviewsCount: 29400,
    distance: 'Mananchira Square, Kozhikode',
    address: 'Aravind Ghosh Rd, Near Mathrubhumi, Kozhikode, Kerala 673001',
    lat: 11.2522,
    lng: 75.7831,
    image: 'https://images.unsplash.com/photo-1563379091339-03b21ab4a4f8?auto=format&fit=crop&w=800&q=80',
    openNow: true,
    openingHours: '06:00 AM - 11:00 PM',
    cuisine: 'Legendary Kozhikode Beef Biryani & Malabar Porotta',
    priceRange: '₹',
    halalCertification: '100% Halal Certified Meat • Family Friendly',
    alcoholFree: true,
    hasPrayerSpace: true,
    popularDishes: ['Famous Beef Biryani', 'Kozhi Porichathu', 'Coin Porotta & Beef Roast', 'Sulaimani'],
  },
  {
    id: 'food-kerala-3',
    name: 'Kayees Rahmathulla Cafe',
    city: 'Kochi (Mattancherry)',
    country: 'India',
    category: 'restaurant',
    rating: 4.8,
    reviewsCount: 18200,
    distance: 'Near Gujarati Street, Mattancherry',
    address: 'Mattancherry, Kochi, Kerala 682002',
    lat: 9.9575,
    lng: 76.2575,
    image: 'https://images.unsplash.com/photo-1633945274405-b6c8069047b0?auto=format&fit=crop&w=800&q=80',
    openNow: true,
    openingHours: '11:30 AM - 09:30 PM (Biryani starts 12:00 PM)',
    cuisine: 'Historic Mattancherry Mutton Biryani since 1951',
    priceRange: '₹₹',
    halalCertification: '100% Halal Meat • Legacy Muslim Dining',
    alcoholFree: true,
    hasPrayerSpace: true,
    popularDishes: ['Kayees Special Mutton Biryani', 'Chicken Roast', 'Fish Fry', 'Date & Lime Pickle'],
  },
  {
    id: 'food-kerala-4',
    name: 'Paris Restaurant',
    city: 'Thalassery (Kannur)',
    country: 'India',
    category: 'restaurant',
    rating: 4.8,
    reviewsCount: 12900,
    distance: 'Thalassery Town Centre',
    address: 'Old Bus Stand Rd, Thalassery, Kannur, Kerala 670101',
    lat: 11.7511,
    lng: 75.4925,
    image: 'https://images.unsplash.com/photo-1589302168068-964664d93dc0?auto=format&fit=crop&w=800&q=80',
    openNow: true,
    openingHours: '07:00 AM - 10:30 PM',
    cuisine: 'Original Thalassery Dum Biryani (Khaima / Jeerakasala Rice)',
    priceRange: '₹₹',
    halalCertification: '100% Halal Verified • Iconic Thalassery Taste',
    alcoholFree: true,
    hasPrayerSpace: true,
    popularDishes: ['Thalassery Dum Biryani', 'Neychoru & Mutton Curry', 'Aleesa', 'Unnakaya'],
  },
  {
    id: 'food-kerala-5',
    name: 'Zain\'s Hotel & Snacks',
    city: 'Kozhikode (Calicut)',
    country: 'India',
    category: 'restaurant',
    rating: 4.8,
    reviewsCount: 8900,
    distance: 'Kozhikode Beachfront Road',
    address: 'Convent Cross Rd, Near Beach, Kozhikode, Kerala 673032',
    lat: 11.2581,
    lng: 75.7699,
    image: 'https://images.unsplash.com/photo-1541432901042-2d8bd64b4a9b?auto=format&fit=crop&w=800&q=80',
    openNow: true,
    openingHours: '12:00 PM - 11:00 PM',
    cuisine: 'Authentic Muslim Home Snacks & Malabar Evening Tea',
    priceRange: '₹',
    halalCertification: '100% Halal • Run by Zainabi Noor',
    alcoholFree: true,
    hasPrayerSpace: true,
    popularDishes: ['Chattipathiri', 'Unnakaya', 'Muthamala', 'Kallummakkaya Nirachathu (Stuffed Mussels)', 'Kozhi Ada'],
  },
  {
    id: 'food-kerala-6',
    name: 'Al Bake & Kuzhimanthi Hub',
    city: 'Mannarkkad (Palakkad)',
    country: 'India',
    category: 'restaurant',
    rating: 4.7,
    reviewsCount: 4200,
    distance: 'Palakkad-Kozhikode Highway, Mannarkkad',
    address: 'Court Road, Mannarkkad, Kerala 678582',
    lat: 10.9888,
    lng: 76.4608,
    image: 'https://images.unsplash.com/photo-1563379091339-03b21ab4a4f8?auto=format&fit=crop&w=800&q=80',
    openNow: true,
    openingHours: '11:00 AM - 11:30 PM',
    cuisine: 'Arabian Mandi, Shawarma & Malabar Grills',
    priceRange: '₹₹',
    halalCertification: '100% Halal Certified Meat • Alcohol-Free',
    alcoholFree: true,
    hasPrayerSpace: true,
    popularDishes: ['Chicken Kuzhimanthi', 'Mutton Madhbi', 'Alfaham Peri Peri', 'Fresh Lime Soda'],
  },
  {
    id: 'food-kerala-7',
    name: '1980\'s A Nostalgic Restaurant',
    city: 'Wayanad (Kalpetta)',
    country: 'India',
    category: 'restaurant',
    rating: 4.8,
    reviewsCount: 16400,
    distance: 'Kalpetta Bypass, Wayanad',
    address: 'Kalpetta, Wayanad, Kerala 673121',
    lat: 11.6055,
    lng: 76.0825,
    image: 'https://images.unsplash.com/photo-1633945274405-b6c8069047b0?auto=format&fit=crop&w=800&q=80',
    openNow: true,
    openingHours: '11:30 AM - 10:30 PM',
    cuisine: 'Authentic Kerala Plantain Leaf Meal & Bamboo Biryani',
    priceRange: '₹₹',
    halalCertification: 'Halal Meat Dishes • Pure Clean Kitchen',
    alcoholFree: true,
    hasPrayerSpace: true,
    popularDishes: ['Bamboo Biryani', 'Kanthari Chicken', 'Karimeen Pollichathu', 'Payasam'],
  },
  {
    id: 'food-kerala-8',
    name: 'Zam Zam Restaurant',
    city: 'Thiruvananthapuram',
    country: 'India',
    category: 'restaurant',
    rating: 4.8,
    reviewsCount: 19800,
    distance: 'Opposite Palayam Juma Masjid',
    address: 'Palayam, Thiruvananthapuram, Kerala 695034',
    lat: 8.5025,
    lng: 76.9518,
    image: 'https://images.unsplash.com/photo-1589302168068-964664d93dc0?auto=format&fit=crop&w=800&q=80',
    openNow: true,
    openingHours: '11:00 AM - 12:00 AM',
    cuisine: 'Arabian Al Faham, Shawarma, Kabsa & Biryani',
    priceRange: '₹₹',
    halalCertification: '100% Halal Certified • Prime Landmark Dining',
    alcoholFree: true,
    hasPrayerSpace: true,
    popularDishes: ['Kanthari Al Faham', 'Rumali Roti & Butter Chicken', 'Chicken Shawarma Plate', 'Arabian Kabsa'],
  },
  {
    id: 'food-kerala-9',
    name: 'Halais Restaurant',
    city: 'Alappuzha (Alleppey)',
    country: 'India',
    category: 'restaurant',
    rating: 4.7,
    reviewsCount: 8200,
    distance: 'Near Alappuzha Railway Station',
    address: 'Boat Jetty Rd, Alappuzha, Kerala 688011',
    lat: 9.4981,
    lng: 76.3388,
    image: 'https://images.unsplash.com/photo-1563379091339-03b21ab4a4f8?auto=format&fit=crop&w=800&q=80',
    openNow: true,
    openingHours: '11:00 AM - 11:00 PM',
    cuisine: 'Backwater Malabar Seafood & Halal Grills',
    priceRange: '₹₹',
    halalCertification: '100% Halal Certified • Family Dining',
    alcoholFree: true,
    hasPrayerSpace: true,
    popularDishes: ['Duck Roast & Appam', 'Malabar Mutton Biryani', 'Fish Mango Curry', 'Fresh Lime'],
  },

  // ==========================================
  // KERALA MUSLIM-FRIENDLY HOTELS & RESORTS
  // ==========================================
  {
    id: 'hotel-kerala-1',
    name: 'The Raviz Kadavu Resort',
    city: 'Kozhikode (Calicut)',
    country: 'India',
    category: 'hotel',
    rating: 4.8,
    reviewsCount: 6400,
    distance: 'Chaliyar Riverfront, NH Bypass',
    address: 'NH 17, Calicut Bypass Road, Azhinjilam, Malappuram / Kozhikode, Kerala 673632',
    lat: 11.1925,
    lng: 75.8565,
    image: 'https://images.unsplash.com/photo-1566073771259-6a8506099945?auto=format&fit=crop&w=800&q=80',
    openNow: true,
    openingHours: '24/7 Front Desk',
    priceRange: '₹₹₹₹',
    facilities: [
      'Qibla Direction marked in all luxury rooms & suites',
      'Prayer Mats available on request',
      '100% Halal certified dining menus & breakfast',
      'Peaceful Chaliyar river views & Ayurvedic spa',
      'Family private pool cottages',
    ],
  },
  {
    id: 'hotel-kerala-2',
    name: 'Grand Hyatt Bolgatty Waterfront',
    city: 'Kochi',
    country: 'India',
    category: 'hotel',
    rating: 4.9,
    reviewsCount: 8900,
    distance: 'Bolgatty Island, Kochi Harbor',
    address: 'Mulavukad, Bolgatty, Kochi, Kerala 682504',
    lat: 9.9885,
    lng: 76.2625,
    image: 'https://images.unsplash.com/photo-1582719478250-c89cae4dc85b?auto=format&fit=crop&w=800&q=80',
    openNow: true,
    openingHours: '24/7 Front Desk',
    priceRange: '₹₹₹₹₹',
    facilities: [
      'Dedicated Quiet Musalla Prayer Room on site',
      'Halal certified banquet & international dining options',
      'Qibla compass markers & prayer rugs in rooms',
      'Vembanad lake backwater views & luxury family suites',
    ],
  },
  {
    id: 'hotel-kerala-3',
    name: 'Vythiri Village Rainforest Resort',
    city: 'Wayanad',
    country: 'India',
    category: 'hotel',
    rating: 4.8,
    reviewsCount: 7200,
    distance: 'Vythiri, Wayanad Hills',
    address: 'Near Town, Vythiri, Wayanad, Kerala 673576',
    lat: 11.5511,
    lng: 76.0415,
    image: 'https://images.unsplash.com/photo-1540555700478-4be289fbecef?auto=format&fit=crop&w=800&q=80',
    openNow: true,
    openingHours: '24/7 Guest Service',
    priceRange: '₹₹₹₹',
    facilities: [
      'Private pool villas with high privacy walls for Muslim families',
      'Halal certified multi-cuisine dining & barbecue',
      'Peaceful prayer area amidst mist-clad Western Ghats forests',
      'Fresh mountain air & eco-friendly walking trails',
    ],
  },
  {
    id: 'hotel-kerala-4',
    name: 'Lake Palace Backwater Resort & Halal Houseboats',
    city: 'Alappuzha (Alleppey)',
    country: 'India',
    category: 'hotel',
    rating: 4.8,
    reviewsCount: 5100,
    distance: 'Thirumala, Punnamada, Alleppey',
    address: 'Punnamada, Alappuzha, Kerala 688006',
    lat: 9.5122,
    lng: 76.3512,
    image: 'https://images.unsplash.com/photo-1566073771259-6a8506099945?auto=format&fit=crop&w=800&q=80',
    openNow: true,
    openingHours: '24/7 Guest Check-in',
    priceRange: '₹₹₹₹',
    facilities: [
      'Private luxury houseboats with 100% Halal chef on board',
      'Prayer times synced with backwater sailing',
      'Spacious sun-decks for congregational prayer facing Qibla',
      'Zero alcohol policy available on request for private charters',
    ],
  },

  // ==========================================
  // KERALA AIRPORTS & TRANSIT PRAYER ROOMS
  // ==========================================
  {
    id: 'musalla-kerala-1',
    name: 'CIAL Cochin Airport Prayer Lounge',
    city: 'Kochi (Nedumbassery)',
    country: 'India',
    category: 'prayer_room',
    rating: 4.9,
    reviewsCount: 4200,
    distance: 'Terminal 3 International Departures & Arrivals',
    address: 'Cochin International Airport, Nedumbassery, Kerala 683111',
    lat: 10.1518,
    lng: 76.3929,
    image: 'https://images.unsplash.com/photo-1590076215667-875d4ef2d7ee?auto=format&fit=crop&w=800&q=80',
    openNow: true,
    openingHours: 'Open 24/7 for All Flights',
    facilities: [
      'Clean running water wudu ablution stations',
      'Separate air-conditioned sections for Brothers and Sisters',
      'Clear Qibla direction indicators, prayer mats & Qurans',
      'Flight announcement speakers inside the prayer lounge',
    ],
    hasWomensArea: true,
    hasWuduArea: true,
    hasWheelchairAccess: true,
  },
  {
    id: 'musalla-kerala-2',
    name: 'Calicut International Airport Musalla',
    city: 'Kozhikode (Karipur)',
    country: 'India',
    category: 'prayer_room',
    rating: 4.9,
    reviewsCount: 5800,
    distance: 'Airport Terminal departures concourse',
    address: 'Calicut International Airport, Karipur, Malappuram, Kerala 673647',
    lat: 11.1364,
    lng: 75.9553,
    image: 'https://images.unsplash.com/photo-1542601906990-b4d3fb778b09?auto=format&fit=crop&w=800&q=80',
    openNow: true,
    openingHours: 'Open 24/7',
    facilities: [
      'Spacious prayer hall serving international Gulf travelers',
      'High-capacity wudu ablution area',
      'Comfortable carpeted space with prayer mats',
      'Convenient access before and after security gates',
    ],
    hasWomensArea: true,
    hasWuduArea: true,
    hasWheelchairAccess: true,
  },
  {
    id: 'musalla-kerala-3',
    name: 'Lulu Mall Kochi Prayer Facility',
    city: 'Kochi (Edappally)',
    country: 'India',
    category: 'prayer_room',
    rating: 4.8,
    reviewsCount: 3900,
    distance: '2nd Floor near food court',
    address: '34/1000, Old NH 47, Edappally, Kochi, Kerala 682024',
    lat: 10.0275,
    lng: 76.3081,
    image: 'https://images.unsplash.com/photo-1564507592333-c60657eea523?auto=format&fit=crop&w=800&q=80',
    openNow: true,
    openingHours: '10:00 AM - 10:30 PM',
    facilities: [
      'Clean modern prayer room for men and women',
      'Foot-washing wudu sinks & slippers provided',
      'Clear Qibla direction & digital prayer clock',
    ],
    hasWomensArea: true,
    hasWuduArea: true,
    hasWheelchairAccess: true,
  },

  // ==========================================
  // KERALA EMERGENCY HOSPITALS (ആശുപത്രികൾ)
  // ==========================================
  {
    id: 'hospital-kerala-1',
    name: 'Aster MIMS Hospital',
    city: 'Kozhikode (Calicut)',
    country: 'India',
    category: 'hospital',
    rating: 4.8,
    reviewsCount: 8900,
    distance: 'Mini Bypass Road, Govindapuram',
    address: 'Mini Bypass Rd, Govindapuram, Kozhikode, Kerala 673016',
    lat: 11.2467,
    lng: 75.8012,
    image: 'https://images.unsplash.com/photo-1519494026892-80bbd2d6fd0d?auto=format&fit=crop&w=800&q=80',
    openNow: true,
    openingHours: '24/7 Emergency & Trauma Care',
    facilities: [
      '24/7 Emergency Ambulance Service (0495 2488000)',
      'Multi-speciality tertiary care hospital & ICU',
      'English, Malayalam & Arabic speaking international patient desk',
      'On-site prayer room & halal dietary services',
    ],
  },
  {
    id: 'hospital-kerala-2',
    name: 'Aster Medcity',
    city: 'Kochi',
    country: 'India',
    category: 'hospital',
    rating: 4.9,
    reviewsCount: 11200,
    distance: 'Kuttisahib Road, Cheranallur',
    address: 'Kuttisahib Road, Near Kothad Bridge, Cheranallur, Kochi, Kerala 682027',
    lat: 10.0545,
    lng: 76.2694,
    image: 'https://images.unsplash.com/photo-1587351021759-3e566b6af7cc?auto=format&fit=crop&w=800&q=80',
    openNow: true,
    openingHours: '24/7 Emergency & ICU',
    facilities: [
      'JCI Accredited Quaternary Care Hub',
      '24/7 Critical Care & Emergency helpline (0484 6699999)',
      'Helipad, water ambulance & world-class facilities',
      'Multi-faith prayer facility and halal meals',
    ],
  },
  {
    id: 'hospital-kerala-3',
    name: 'Taluk Hospital & Mother Care',
    city: 'Mannarkkad (Palakkad)',
    country: 'India',
    category: 'hospital',
    rating: 4.6,
    reviewsCount: 1800,
    distance: 'Mannarkkad Town Centre',
    address: 'Hospital Junction, Mannarkkad, Palakkad District, Kerala 678582',
    lat: 10.9888,
    lng: 76.4608,
    image: 'https://images.unsplash.com/photo-1519494026892-80bbd2d6fd0d?auto=format&fit=crop&w=800&q=80',
    openNow: true,
    openingHours: '24/7 Casualty & Emergency',
    facilities: [
      '24/7 Government & Emergency Care (04924 222345)',
      'Ambulance dispatch & trauma stabilisation',
      'Immediate medical aid for Silent Valley travelers',
    ],
  },
];
