import { Place } from '../types';

export const INITIAL_PLACES: Place[] = [
  // ==========================================
  // INDIA & KERALA MOSQUES
  // ==========================================
  {
    id: 'mosque-ind-1',
    name: 'Cheraman Juma Masjid',
    city: 'Kochi (Kerala)',
    country: 'India',
    category: 'mosque',
    rating: 4.9,
    reviewsCount: 12340,
    distance: '38 km (Kodungallur)',
    address: 'Paravur - Kodungallur Rd, Padakulam, Kodungallur, Kerala 680664',
    lat: 10.2155,
    lng: 76.2003,
    image: 'https://images.unsplash.com/photo-1590076215667-875d4ef2d7ee?auto=format&fit=crop&w=800&q=80',
    openNow: true,
    openingHours: 'Open 24/7 for Salah & Visitors',
    facilities: [
      'Built in 629 CE (India\'s Oldest Mosque)',
      'Historic 1400-Year Ancient Brass Oil Lamp',
      'Islamic Heritage Museum',
      'Spacious Wudu Pond & Running Taps',
      'Women\'s Prayer Section',
    ],
    hasWomensArea: true,
    hasWuduArea: true,
    hasWheelchairAccess: true,
    jumuaTime: '12:45 PM (Khutbah in Malayalam & Arabic)',
  },
  {
    id: 'mosque-ind-2',
    name: 'Mishkal Mosque (Mishkal Palli)',
    city: 'Kozhikode (Calicut)',
    country: 'India',
    category: 'mosque',
    rating: 4.9,
    reviewsCount: 8920,
    distance: '1.2 km from Beach',
    address: 'Kuttichira, Kozhikode (Calicut), Kerala 673001',
    lat: 11.2435,
    lng: 75.7766,
    image: 'https://images.unsplash.com/photo-1542601906990-b4d3fb778b09?auto=format&fit=crop&w=800&q=80',
    openNow: true,
    openingHours: '04:30 AM - 10:00 PM',
    facilities: [
      '14th Century Four-Tiered Teak Architecture',
      'Historic Kuttichira Ablution Pond (Kulam)',
      'Rich Arab-Malabar Maritime Heritage',
      'Dedicated Women\'s Prayer Area',
      'Active 5 Daily Congregations',
    ],
    hasWomensArea: true,
    hasWuduArea: true,
    hasWheelchairAccess: false,
    jumuaTime: '13:00 PM (Friday Jumu\'ah with Malayalam Bayan)',
  },
  {
    id: 'mosque-ind-3',
    name: 'Palayam Juma Masjid (Masjid-i Jahan-Numa)',
    city: 'Thiruvananthapuram',
    country: 'India',
    category: 'mosque',
    rating: 4.8,
    reviewsCount: 6540,
    distance: '500 m from Central Station',
    address: 'Palayam, Thiruvananthapuram, Kerala 695034',
    lat: 8.5028,
    lng: 76.9515,
    image: 'https://images.unsplash.com/photo-1564507592333-c60657eea523?auto=format&fit=crop&w=800&q=80',
    openNow: true,
    openingHours: 'Open for all 5 daily prayers',
    facilities: [
      'Heart of Capital City Trivandrum',
      'Air-conditioned Main Prayer Hall',
      'Friday Khutbah with Malayalam Translation',
      'Extensive Women\'s Wing with Separate Entry',
      'Wheelchair Ramps & Clean Ablution Block',
    ],
    hasWomensArea: true,
    hasWuduArea: true,
    hasWheelchairAccess: true,
    jumuaTime: '12:45 PM',
  },
  {
    id: 'mosque-ind-4',
    name: 'Jama Masjid (Old Delhi)',
    city: 'New Delhi',
    country: 'India',
    category: 'mosque',
    rating: 4.8,
    reviewsCount: 34100,
    distance: '300 m from Chandni Chowk',
    address: 'Jama Masjid Rd, Chandni Chowk, New Delhi, Delhi 110006',
    lat: 28.6507,
    lng: 77.2334,
    image: 'https://images.unsplash.com/photo-1584551246679-0daf3d275d0f?auto=format&fit=crop&w=800&q=80',
    openNow: true,
    openingHours: '05:00 AM - 09:30 PM (Closed to visitors during Salah)',
    facilities: [
      'Built in 1656 by Mughal Emperor Shah Jahan',
      'Accommodates 25,000 Worshippers in Courtyard',
      'Historic Sacred Relics Pavilion',
      'Central Wudu Ablution Pool',
      'Historic Minaret Panoramic Views of Delhi',
    ],
    hasWomensArea: true,
    hasWuduArea: true,
    hasWheelchairAccess: true,
    jumuaTime: '13:15 PM',
  },
  {
    id: 'mosque-ind-5',
    name: 'Makkah Masjid (Hyderabad)',
    city: 'Hyderabad',
    country: 'India',
    category: 'mosque',
    rating: 4.8,
    reviewsCount: 18900,
    distance: '150 m from Charminar',
    address: 'Near Charminar, Ghansi Bazaar, Hyderabad, Telangana 500002',
    lat: 17.3606,
    lng: 78.4735,
    image: 'https://images.unsplash.com/photo-1541432901042-2d8bd64b4a9b?auto=format&fit=crop&w=800&q=80',
    openNow: true,
    openingHours: '04:00 AM - 09:30 PM',
    facilities: [
      'Bricks Made from Holy Soil of Makkah',
      'Vast Granite Colonnades & Arches',
      'Large Central Ablution Pond',
      'Wheelchair Accessibility Ramps',
      'Daily Jama\'at and Historic Relics',
    ],
    hasWomensArea: true,
    hasWuduArea: true,
    hasWheelchairAccess: true,
    jumuaTime: '13:00 PM',
  },
  {
    id: 'mosque-ind-6',
    name: 'Ponnani Valiya Juma Masjid',
    city: 'Ponnani (Kerala)',
    country: 'India',
    category: 'mosque',
    rating: 4.9,
    reviewsCount: 7820,
    distance: 'Heart of Historic Ponnani Harbour',
    address: 'Halve Street, Ponnani, Malappuram, Kerala 679577',
    lat: 10.7672,
    lng: 75.925,
    image: 'https://images.unsplash.com/photo-1590076215667-875d4ef2d7ee?auto=format&fit=crop&w=800&q=80',
    openNow: true,
    openingHours: 'Open 24/7 for Congregations',
    facilities: [
      'Built in 1519 CE by Sheikh Zainuddin Makhdoom I',
      'Historical "Little Makkah" of Malabar & Islamic Seminary',
      'Ancient "Vilakkilirikkal" Traditional Scholar Circle Lamp',
      'Exquisite Malabar Timber Carvings & Calligraphy',
      'Spacious Traditional Ablution Pond & Separate Ladies Area',
    ],
    hasWomensArea: true,
    hasWuduArea: true,
    hasWheelchairAccess: true,
    jumuaTime: '12:45 PM (Khutbah with Malayalam guidance)',
  },
  {
    id: 'mosque-ind-7',
    name: 'Malik Deenar Great Juma Masjid',
    city: 'Kasaragod (Kerala)',
    country: 'India',
    category: 'mosque',
    rating: 4.9,
    reviewsCount: 9400,
    distance: '3.5 km from Kasaragod Railway Station',
    address: 'Thalangara, Kasaragod, Kerala 671122',
    lat: 12.5102,
    lng: 74.9852,
    image: 'https://images.unsplash.com/photo-1542601906990-b4d3fb778b09?auto=format&fit=crop&w=800&q=80',
    openNow: true,
    openingHours: '04:30 AM - 10:30 PM',
    facilities: [
      'Founded by Malik ibn Dinar (RA) in 7th Century',
      'Scenic Arabian Sea Coast & Estuary Breeze',
      'Grave of Malik ibn Dinar inside the Complex',
      'Extensive Heritage Courtyards & Ablution Pool',
      'Large Congregational Capacity for Friday Jumu\'ah',
    ],
    hasWomensArea: true,
    hasWuduArea: true,
    hasWheelchairAccess: true,
    jumuaTime: '13:00 PM',
  },
  {
    id: 'mosque-ind-8',
    name: 'Muchundi Mosque (Ancient Kuttichira Heritage)',
    city: 'Kozhikode (Calicut)',
    country: 'India',
    category: 'mosque',
    rating: 4.8,
    reviewsCount: 4620,
    distance: '400 m from Mishkal Mosque',
    address: 'Kuttichira, Kozhikode, Kerala 673001',
    lat: 11.2415,
    lng: 75.7788,
    image: 'https://images.unsplash.com/photo-1564507592333-c60657eea523?auto=format&fit=crop&w=800&q=80',
    openNow: true,
    openingHours: 'Open for 5 Daily Prayers',
    facilities: [
      '13th-Century Stone Decree Gifted by Hindu Zamorin King',
      'Ancient Old Malayalam Vatteluttu Script Inscription',
      'Traditional Gabled Wooden Roof & Intricate Carvings',
      'Serene Kuttichira Community Quarter',
    ],
    hasWomensArea: true,
    hasWuduArea: true,
    hasWheelchairAccess: false,
    jumuaTime: '12:50 PM',
  },
  {
    id: 'mosque-ind-9',
    name: 'Hazratbal Shrine & Mosque',
    city: 'Srinagar (Kashmir)',
    country: 'India',
    category: 'mosque',
    rating: 4.9,
    reviewsCount: 22100,
    distance: 'On Western Shore of Dal Lake',
    address: 'Hazratbal, Srinagar, Jammu and Kashmir 190006',
    lat: 34.1258,
    lng: 74.8423,
    image: 'https://images.unsplash.com/photo-1584551246679-0daf3d275d0f?auto=format&fit=crop&w=800&q=80',
    openNow: true,
    openingHours: '04:00 AM - 10:00 PM',
    facilities: [
      'Pristine White Marble Domes overlooking Dal Lake',
      'Houses the Holy Relic (Moi-e-Muqaddas)',
      'Snow-capped Himalayan Mountain Backdrop',
      'Vast Peaceful Courtyard & Shikara Boat Access',
      'Womens Prayer Pavilion & Clean Ablution',
    ],
    hasWomensArea: true,
    hasWuduArea: true,
    hasWheelchairAccess: true,
    jumuaTime: '13:15 PM',
  },
  {
    id: 'mosque-ind-10',
    name: 'Haji Ali Dargah & Mosque',
    city: 'Mumbai',
    country: 'India',
    category: 'mosque',
    rating: 4.8,
    reviewsCount: 36700,
    distance: 'Worli Sea Face / Mahalaxmi',
    address: 'Dargah Rd, Haji Ali, Mumbai, Maharashtra 400026',
    lat: 18.9827,
    lng: 72.8089,
    image: 'https://images.unsplash.com/photo-1541432901042-2d8bd64b4a9b?auto=format&fit=crop&w=800&q=80',
    openNow: true,
    openingHours: '05:30 AM - 10:00 PM (Subject to Tide)',
    facilities: [
      'Iconic 1431 CE Mosque on Islet in Arabian Sea',
      'Scenic Ocean Causeway Walkway',
      'Indo-Islamic Architectural Minarets',
      'Dedicated Qawwali & Dhikr Gatherings',
      'Daily 5 Congregational Salah & Ablution Area',
    ],
    hasWomensArea: true,
    hasWuduArea: true,
    hasWheelchairAccess: false,
    jumuaTime: '13:00 PM',
  },

  // ==========================================
  // INDIA & KERALA HALAL FOOD
  // ==========================================
  {
    id: 'food-ind-1',
    name: 'Paragon Restaurant (Kozhikode & Kochi)',
    city: 'Kozhikode (Calicut)',
    country: 'India',
    category: 'restaurant',
    cuisine: 'Authentic Malabar Biryani, Seafood & Porotta',
    rating: 4.9,
    reviewsCount: 28400,
    distance: '850 m from Railway Station',
    address: 'Kannur Road, Near CH Flyover, Kozhikode, Kerala 673001',
    lat: 11.2588,
    lng: 75.7804,
    image: 'https://images.unsplash.com/photo-1563379091339-03b21ab4a4f8?auto=format&fit=crop&w=800&q=80',
    openNow: true,
    openingHours: '06:00 AM - 12:30 AM',
    halalStatus: 'verified',
    facilities: [
      '100% Halal Meat Certified by Malabar Scholars',
      'Strictly Alcohol-Free Family Dining',
      'World-Famous Kozhikode Dum Biryani',
      'Signature Malabar Fish Mango Curry',
      'Dedicated Prayer Mat & Wudu Facilities on request',
    ],
    priceRange: '€€',
    alcoholFree: true,
  },
  {
    id: 'food-ind-2',
    name: 'Kayees Rahmathulla Cafe',
    city: 'Kochi (Kerala)',
    country: 'India',
    category: 'restaurant',
    cuisine: 'Traditional Mattancherry Dum Mutton Biryani',
    rating: 4.7,
    reviewsCount: 14200,
    distance: '1.2 km from Fort Kochi Pier',
    address: 'Gujarati Rd, Near Police Station, Mattancherry, Kochi, Kerala 682002',
    lat: 9.9575,
    lng: 76.2599,
    image: 'https://images.unsplash.com/photo-1589302168068-964664d93dc0?auto=format&fit=crop&w=800&q=80',
    openNow: true,
    openingHours: '11:30 AM - 04:00 PM, 06:30 PM - 10:00 PM',
    halalStatus: 'verified',
    facilities: [
      'Historic Malabar Heritage Recipe Since 1948',
      '100% Halal Slaughtered Goat Meat',
      'Strictly Alcohol-Free Environment',
      'Traditional Neyyappam & Sulaimani Tea',
    ],
    priceRange: '€€',
    alcoholFree: true,
  },
  {
    id: 'food-ind-3',
    name: 'Dhe Puttu',
    city: 'Kochi (Kerala)',
    country: 'India',
    category: 'restaurant',
    cuisine: 'Kerala Heritage Steamed Puttu & Malabar Curries',
    rating: 4.6,
    reviewsCount: 9800,
    distance: '2.5 km from Lulu Mall',
    address: 'Service Rd, Near Toll Gate, Edappally, Kochi, Kerala 682024',
    lat: 10.0261,
    lng: 76.3082,
    image: 'https://images.unsplash.com/photo-1540420773420-3366772f4999?auto=format&fit=crop&w=800&q=80',
    openNow: true,
    openingHours: '08:00 AM - 11:00 PM',
    halalStatus: 'verified',
    facilities: [
      'Authentic Kerala Malabar Specialties',
      'Halal Chicken, Beef & Mutton curries',
      'Alcohol-Free Family Ambience',
      'High Chairs & Valet Parking',
    ],
    priceRange: '€€',
    alcoholFree: true,
  },
  {
    id: 'food-ind-4',
    name: 'Karim\'s (Original Historic Branch)',
    city: 'New Delhi',
    country: 'India',
    category: 'restaurant',
    cuisine: 'Royal Mughlai Kebabs, Mutton Burra & Nahari',
    rating: 4.8,
    reviewsCount: 38900,
    distance: '50 m from Jama Masjid Gate 1',
    address: '16 Gali Kababian, Jama Masjid, Old Delhi, Delhi 110006',
    lat: 28.6514,
    lng: 77.2339,
    image: 'https://images.unsplash.com/photo-1555939594-58d7cb561ad1?auto=format&fit=crop&w=800&q=80',
    openNow: true,
    openingHours: '09:00 AM - 01:00 AM',
    halalStatus: 'verified',
    facilities: [
      'Established in 1913 by Royal Mughal Chefs',
      '100% Halal Slaughtered Meat Only',
      'Strictly Alcohol-Free',
      'Steps away from Jama Masjid for Salah',
    ],
    priceRange: '€€',
    alcoholFree: true,
  },
  {
    id: 'food-ind-5',
    name: 'Hotel Shadab',
    city: 'Hyderabad',
    country: 'India',
    category: 'restaurant',
    cuisine: 'Authentic Hyderabadi Dum Biryani, Haleem & Irani Chai',
    rating: 4.8,
    reviewsCount: 26500,
    distance: '200 m from Madina Circle, Charminar',
    address: 'High Court Rd, Madina Circle, Ghansi Bazaar, Hyderabad, Telangana 500002',
    lat: 17.3639,
    lng: 78.4732,
    image: 'https://images.unsplash.com/photo-1544025162-d76694265947?auto=format&fit=crop&w=800&q=80',
    openNow: true,
    openingHours: '05:30 AM - 02:00 AM',
    halalStatus: 'verified',
    facilities: [
      'Iconic Hyderabadi Mutton Dum Biryani',
      '100% Halal Certified Meat',
      'Alcohol-Free',
      'Morning Nahari & Osmania Biscuits with Chai',
    ],
    priceRange: '€€',
    alcoholFree: true,
  },
  {
    id: 'food-ind-6',
    name: 'Rahmath Restaurant (Calicut)',
    city: 'Kozhikode (Calicut)',
    country: 'India',
    category: 'restaurant',
    cuisine: 'Legendary Kozhikodan Beef Dum Biryani & Sulaimani',
    rating: 4.8,
    reviewsCount: 19800,
    distance: '600 m from Kozhikode Beach',
    address: 'Near Mathrubhumi Office, KP Kesava Menon Rd, Kozhikode, Kerala 673001',
    lat: 11.2514,
    lng: 75.7765,
    image: 'https://images.unsplash.com/photo-1563379091339-03b21ab4a4f8?auto=format&fit=crop&w=800&q=80',
    openNow: true,
    openingHours: '06:30 AM - 11:30 PM',
    halalStatus: 'verified',
    facilities: [
      'Renowned for Authentic Malabar Beef Biryani',
      '100% Halal Meat & Traditional Kerala Wood-fired Dum',
      'Famous Black Tea (Sulaimani) with Mint and Cardamom',
      'Alcohol-Free Family Atmosphere',
      'Prayer Area Available Upstairs',
    ],
    priceRange: '€€',
    alcoholFree: true,
  },
  {
    id: 'food-ind-7',
    name: 'Zains Malabar Traditional Cuisine',
    city: 'Kozhikode (Calicut)',
    country: 'India',
    category: 'restaurant',
    cuisine: 'Authentic Mappila Heritage Delicacies & Tea Snacks',
    rating: 4.7,
    reviewsCount: 11200,
    distance: 'Convent Cross Rd, Kozhikode Beach',
    address: 'Convent Cross Rd, Near Beach, Kozhikode, Kerala 673032',
    lat: 11.2541,
    lng: 75.7712,
    image: 'https://images.unsplash.com/photo-1589302168068-964664d93dc0?auto=format&fit=crop&w=800&q=80',
    openNow: true,
    openingHours: '12:00 PM - 10:30 PM',
    halalStatus: 'verified',
    facilities: [
      'Pioneering Mappila Woman Chef Zainabi Noor Recipe Legacy',
      'Chatti Pathiri, Unnakaya, Erachi Pathiri & Kallummakkaya',
      '100% Halal Certified Family Dining',
      'Alcohol-Free Environment',
    ],
    priceRange: '€€',
    alcoholFree: true,
  },
  {
    id: 'food-ind-8',
    name: 'MVK Restaurant (Thalassery & Kannur)',
    city: 'Kannur (Kerala)',
    country: 'India',
    category: 'restaurant',
    cuisine: 'Original Thalassery Dum Biryani (Khaima Rice)',
    rating: 4.8,
    reviewsCount: 15400,
    distance: '300 m from Kannur Railway Station',
    address: 'Near Old Bus Stand, Fort Rd, Kannur, Kerala 670001',
    lat: 11.8745,
    lng: 75.3704,
    image: 'https://images.unsplash.com/photo-1555939594-58d7cb561ad1?auto=format&fit=crop&w=800&q=80',
    openNow: true,
    openingHours: '07:00 AM - 11:00 PM',
    halalStatus: 'verified',
    facilities: [
      'Authentic Malabar Khaima Jeerakasala Rice Dum Biryani',
      'Halal Slaughtered Malabar Poultry & Meat',
      'Traditional Neypathiri & Kozhi Curry',
      'Strictly Alcohol-Free',
    ],
    priceRange: '€€',
    alcoholFree: true,
  },
  {
    id: 'food-ind-9',
    name: 'Nahdi Kuzhimanthi & Arabian Grill',
    city: 'Malappuram (Kerala)',
    country: 'India',
    category: 'restaurant',
    cuisine: 'Authentic Yemeni Mandi & Charcoal Grilled Chicken',
    rating: 4.7,
    reviewsCount: 8700,
    distance: 'Kottakkal Byepass / Malappuram Town',
    address: 'Down Hill, Malappuram, Kerala 676505',
    lat: 11.051,
    lng: 76.0711,
    image: 'https://images.unsplash.com/photo-1544025162-d76694265947?auto=format&fit=crop&w=800&q=80',
    openNow: true,
    openingHours: '11:00 AM - 12:00 Midnight',
    halalStatus: 'verified',
    facilities: [
      'Floor Seating (Majlis) & Traditional Family Cabins',
      'Authentic Tandoor Pit-Smoked Kuzhimanthi',
      '100% Halal Certified Meat & Chicken',
      'Alcohol-Free Environment',
      'Spacious Wudu & Prayer Room Facilities',
    ],
    priceRange: '€€',
    alcoholFree: true,
  },

  // ==========================================
  // INDIA & KERALA MUSLIM-FRIENDLY HOTELS
  // ==========================================
  {
    id: 'hotel-ind-1',
    name: 'The Raviz Kadavu Resort & Ayurvedic Spa',
    city: 'Kozhikode (Calicut)',
    country: 'India',
    category: 'hotel',
    rating: 4.9,
    reviewsCount: 3800,
    distance: '14 km from Calicut International Airport (CCJ)',
    address: 'NH 17, Calicut Bypass Road, Azhinjilam, Malappuram/Kozhikode, Kerala 673632',
    lat: 11.1648,
    lng: 75.8715,
    image: 'https://images.unsplash.com/photo-1566073771259-6a8506099945?auto=format&fit=crop&w=800&q=80',
    openNow: true,
    facilities: [
      'Scenic Chaliyar River Backwater Retreat',
      '100% Halal Dining Options in All Restaurants',
      'In-Room Qibla Direction Markers & Prayer Mats Provided',
      'On-site Quiet Prayer Hall for Guests',
      'Family-Friendly Suites & Alcohol-Free Villa Options',
    ],
    priceRange: '€€€',
    qiblaAvailable: true,
    alcoholFree: false,
  },
  {
    id: 'hotel-ind-2',
    name: 'Brunton Boatyard - CGH Earth',
    city: 'Kochi (Kerala)',
    country: 'India',
    category: 'hotel',
    rating: 4.8,
    reviewsCount: 2400,
    distance: '300 m from Fort Kochi Beach & Historic Mosques',
    address: '1/498, Calvathy Rd, Fort Kochi, Kochi, Kerala 682001',
    lat: 9.9678,
    lng: 76.2415,
    image: 'https://images.unsplash.com/photo-1582719508461-905c673771fd?auto=format&fit=crop&w=800&q=80',
    openNow: true,
    facilities: [
      'Restored Colonial Heritage on Harbor',
      'Halal Culinary Choices Prepared Fresh',
      'Prayer Mats Available Upon Request',
      'Walking Distance to Mattancherry & Fort Kochi Mosques',
      'Peaceful Harbor Balconies',
    ],
    priceRange: '€€€€',
    qiblaAvailable: true,
    alcoholFree: false,
  },
  {
    id: 'hotel-ind-3',
    name: 'Vythiri Village Resort & Nature Retreat',
    city: 'Wayanad (Kerala)',
    country: 'India',
    category: 'hotel',
    rating: 4.8,
    reviewsCount: 3100,
    distance: 'Misty Western Ghats, Wayanad',
    address: 'Near Vythiri Town, Wayanad, Kerala 673576',
    lat: 11.5516,
    lng: 76.0426,
    image: 'https://images.unsplash.com/photo-1566073771259-6a8506099945?auto=format&fit=crop&w=800&q=80',
    openNow: true,
    facilities: [
      'Spacious Private Pool Villas in Rainforest',
      '100% Halal Certified Kitchen & Dining',
      'In-Room Prayer Mats & Qibla Direction Markers',
      'On-site Quiet Congregational Prayer Space',
      'Family-Friendly Non-Alcoholic Environment',
    ],
    priceRange: '€€€',
    qiblaAvailable: true,
    alcoholFree: true,
  },
  {
    id: 'hotel-ind-4',
    name: 'Punnamada Resort & Halal Backwater Cruises',
    city: 'Alappuzha (Alleppey)',
    country: 'India',
    category: 'hotel',
    rating: 4.8,
    reviewsCount: 2200,
    distance: 'Vembanad Lake Backwaters',
    address: 'Punnamada, Alappuzha, Kerala 688006',
    lat: 9.5085,
    lng: 76.3508,
    image: 'https://images.unsplash.com/photo-1582719508461-905c673771fd?auto=format&fit=crop&w=800&q=80',
    openNow: true,
    facilities: [
      'Private Family Luxury Houseboats with Halal Chef Aboard',
      'In-Cabin Qibla Direction Compass & Prayer Rugs',
      'Authentic Kerala Backwater Serenity',
      'Strictly Alcohol-Free Private Charters on Request',
    ],
    priceRange: '€€€€',
    qiblaAvailable: true,
    alcoholFree: true,
  },
  {
    id: 'hotel-ind-5',
    name: 'Grand Hyatt Kochi Bolgatty',
    city: 'Kochi (Kerala)',
    country: 'India',
    category: 'hotel',
    rating: 4.9,
    reviewsCount: 4600,
    distance: 'Bolgatty Island Waterfront, Kochi',
    address: 'Mulavukad, Bolgatty, Kochi, Kerala 682504',
    lat: 9.9915,
    lng: 76.2652,
    image: 'https://images.unsplash.com/photo-1542314831-068cd1dbfeeb?auto=format&fit=crop&w=800&q=80',
    openNow: true,
    facilities: [
      'Lakefront Luxury with Panoramic Vembanad Lake Views',
      'Custom Halal Arabic & Malabar Menus (Certified Poultry & Lamb)',
      'Executive Prayer Rooms on Property',
      'Qibla Direction Compass & Mats Provided in All Rooms',
    ],
    priceRange: '€€€€',
    qiblaAvailable: true,
    alcoholFree: false,
  },

  // ==========================================
  // INDIA & KERALA PRAYER ROOMS & HOSPITALS
  // ==========================================
  {
    id: 'prayer-ind-1',
    name: 'Cochin International Airport (CIAL) Prayer Lounge',
    city: 'Kochi (Kerala)',
    country: 'India',
    category: 'prayer_room',
    rating: 4.9,
    reviewsCount: 1850,
    distance: 'Terminal 3 International Departures',
    address: 'Airport Rd, Nedumbassery, Kochi, Kerala 683111',
    lat: 10.1518,
    lng: 76.393,
    image: 'https://images.unsplash.com/photo-1542601906990-b4d3fb778b09?auto=format&fit=crop&w=800&q=80',
    openNow: true,
    openingHours: '24/7 Throughout Flight Operations',
    facilities: [
      'Dedicated Men\'s & Women\'s Prayer Halls',
      'Clean Automatic Ablution (Wudu) Basins',
      'Clear Qibla Direction on Ceiling & Carpet',
      'Comfortable Air-conditioned Quiet Space',
    ],
    hasWomensArea: true,
    hasWuduArea: true,
  },
  {
    id: 'prayer-ind-2',
    name: 'Calicut International Airport (CCJ) Departure Prayer Pavilion',
    city: 'Kozhikode (Calicut)',
    country: 'India',
    category: 'prayer_room',
    rating: 4.8,
    reviewsCount: 1420,
    distance: 'Departure Concourse, CCJ Airport',
    address: 'Calicut Airport P.O, Karipur, Malappuram, Kerala 673647',
    lat: 11.1362,
    lng: 75.9553,
    image: 'https://images.unsplash.com/photo-1590076215667-875d4ef2d7ee?auto=format&fit=crop&w=800&q=80',
    openNow: true,
    openingHours: '24/7 During Flight Schedule',
    facilities: [
      'Spacious Departure & Arrival Prayer Pavilions',
      'Separate Sections for Men & Women',
      'Wudu Washing Area with Running Taps',
      'Accurate Qibla Compass Heading',
    ],
    hasWomensArea: true,
    hasWuduArea: true,
  },
  {
    id: 'prayer-ind-3',
    name: 'Lulu Mall Kochi Prayer Halls & Wudu Suites',
    city: 'Kochi (Kerala)',
    country: 'India',
    category: 'prayer_room',
    rating: 4.9,
    reviewsCount: 2980,
    distance: 'Level 2 & Level 3, Lulu International Shopping Mall',
    address: '34/1000, Old NH 47, Edappally Junction, Kochi, Kerala 682024',
    lat: 10.0278,
    lng: 76.308,
    image: 'https://images.unsplash.com/photo-1564507592333-c60657eea523?auto=format&fit=crop&w=800&q=80',
    openNow: true,
    openingHours: '10:00 AM - 11:00 PM',
    facilities: [
      'Large Air-conditioned Prayer Halls for Men & Women',
      'Dedicated Foot-Washing & Ablution Counters',
      'Imam-led Jumu\'ah & Daily Congregations',
      'Direct Elevator Access from Car Park',
    ],
    hasWomensArea: true,
    hasWuduArea: true,
  },
  {
    id: 'hospital-ind-1',
    name: 'Aster Medcity (International Patient Care)',
    city: 'Kochi (Kerala)',
    country: 'India',
    category: 'hospital',
    rating: 4.9,
    reviewsCount: 5200,
    distance: 'Kochi Waterfront Medical Campus',
    address: 'Kuttisahib Road, Cheranalloor, South Chittoor, Kochi, Kerala 682027',
    lat: 10.0465,
    lng: 76.2625,
    image: 'https://images.unsplash.com/photo-1586773860418-d37222d8fce3?auto=format&fit=crop&w=800&q=80',
    openNow: true,
    openingHours: '24/7 Emergency & Critical Care',
    facilities: [
      'JCI-Accredited Quaternary Healthcare Hub',
      'Dedicated Arabic, English & Malayalam Translators',
      'On-site Multi-Faith Prayer Rooms & Wudu Stations',
      'Halal Dietary Patient Meal Options',
      '24/7 Emergency Hotline (+91 484 6699999)',
    ],
    phone: '+91 484 6699999',
  },
  {
    id: 'hospital-ind-2',
    name: 'Aster MIMS Hospital (Kozhikode)',
    city: 'Kozhikode (Calicut)',
    country: 'India',
    category: 'hospital',
    rating: 4.8,
    reviewsCount: 4100,
    distance: 'Mini Bypass Rd, Govindapuram',
    address: 'Mini Bypass Rd, Govindapuram, Kozhikode, Kerala 673016',
    lat: 11.2592,
    lng: 75.8015,
    image: 'https://images.unsplash.com/photo-1586773860418-d37222d8fce3?auto=format&fit=crop&w=800&q=80',
    openNow: true,
    openingHours: '24/7 Emergency & Trauma Center',
    facilities: [
      'Level 1 Trauma & Emergency Medical Facility',
      'Dedicated Multilingual Patient Assistance',
      'Prayer Area and Clean Ablution Rooms on Level 1',
      'Emergency Dispatch (+91 495 2488000)',
    ],
    phone: '+91 495 2488000',
  },
  {
    id: 'hospital-ind-3',
    name: 'KIMSHEALTH International Medical Center',
    city: 'Thiruvananthapuram',
    country: 'India',
    category: 'hospital',
    rating: 4.8,
    reviewsCount: 3800,
    distance: 'Anayara, Thiruvananthapuram',
    address: 'P.B. No. 1, Anayara P.O., Thiruvananthapuram, Kerala 695029',
    lat: 8.5085,
    lng: 76.9142,
    image: 'https://images.unsplash.com/photo-1586773860418-d37222d8fce3?auto=format&fit=crop&w=800&q=80',
    openNow: true,
    openingHours: '24/7 Emergency Care',
    facilities: [
      'Comprehensive Multi-specialty Healthcare',
      'International Patient Department with Arabic Facilitators',
      'On-site Prayer Facilities',
      'Round-the-clock Ambulance Dispatch (+91 471 3041000)',
    ],
    phone: '+91 471 3041000',
  },

  // ==========================================
  // ISTANBUL, TÜRKIYE (CORE DEMO DESTINATION)
  // ==========================================
  {
    id: 'mosque-1',
    name: 'Sultanahmet Mosque (Blue Mosque)',
    city: 'Istanbul',
    country: 'Türkiye',
    category: 'mosque',
    rating: 4.9,
    reviewsCount: 18450,
    distance: '450 m',
    address: 'Sultan Ahmet, Atmeydanı Cd. No:7, 34122 Fatih/Istanbul',
    lat: 41.0054,
    lng: 28.9768,
    image: 'https://images.unsplash.com/photo-1541432901042-2d8bd64b4a9b?auto=format&fit=crop&w=800&q=80',
    openNow: true,
    openingHours: 'Open 24 Hours for Prayers',
    facilities: ['Wudu Area', 'Women\'s Prayer Section', 'Wheelchair Access', 'Historic Courtyard', 'Adhan Audio'],
    hasWomensArea: true,
    hasWuduArea: true,
    hasWheelchairAccess: true,
    jumuaTime: '13:00 (Khutbah in Turkish & Arabic)',
  },
  {
    id: 'mosque-2',
    name: 'Hagia Sophia Grand Mosque (Ayasofya)',
    city: 'Istanbul',
    country: 'Türkiye',
    category: 'mosque',
    rating: 4.9,
    reviewsCount: 22890,
    distance: '650 m',
    address: 'Sultan Ahmet, Ayasofya Meydanı No:1, 34122 Fatih/Istanbul',
    lat: 41.0086,
    lng: 28.9802,
    image: 'https://images.unsplash.com/photo-1527838832700-5059252407fa?auto=format&fit=crop&w=800&q=80',
    openNow: true,
    openingHours: 'Open for all 5 daily prayers',
    facilities: ['Active Congregation', 'Extensive Carpeting', 'Dedicated Women\'s Section', 'Security Check'],
    hasWomensArea: true,
    hasWuduArea: true,
    hasWheelchairAccess: true,
    jumuaTime: '13:00',
  },
  {
    id: 'mosque-3',
    name: 'Süleymaniye Mosque (Süleymaniye Camii)',
    city: 'Istanbul',
    country: 'Türkiye',
    category: 'mosque',
    rating: 4.9,
    reviewsCount: 14200,
    distance: '1.4 km',
    address: 'Süleymaniye, Prof. Sıddık Sami Onar Cd. No:1, 34116 Fatih/Istanbul',
    lat: 41.0163,
    lng: 28.964,
    image: 'https://images.unsplash.com/photo-1564507592333-c60657eea523?auto=format&fit=crop&w=800&q=80',
    openNow: true,
    openingHours: '05:00 - 22:00',
    facilities: ['Panoramic Golden Horn View', 'Ablution Fountains', 'Women\'s Gallery', 'Peaceful Gardens'],
    hasWomensArea: true,
    hasWuduArea: true,
    hasWheelchairAccess: true,
    jumuaTime: '13:15',
  },
  {
    id: 'mosque-4',
    name: 'Fatih Mosque (Fatih Camii)',
    city: 'Istanbul',
    country: 'Türkiye',
    category: 'mosque',
    rating: 4.8,
    reviewsCount: 8900,
    distance: '2.8 km',
    address: 'Hattat Nafiz Cd. No:6, 34083 Fatih/Istanbul',
    lat: 41.0197,
    lng: 28.9499,
    image: 'https://images.unsplash.com/photo-1565552645632-d725f8bfc19a?auto=format&fit=crop&w=800&q=80',
    openNow: true,
    openingHours: 'Open 24/7 for Salah',
    facilities: ['Madrasa Complex', 'Deep Islamic History', 'Large Wudu Facilities', 'Women\'s Upper Balcony'],
    hasWomensArea: true,
    hasWuduArea: true,
    hasWheelchairAccess: true,
    jumuaTime: '13:00',
  },
  {
    id: 'mosque-5',
    name: 'Ortaköy Mosque (Büyük Mecidiye Camii)',
    city: 'Istanbul',
    country: 'Türkiye',
    category: 'mosque',
    rating: 4.8,
    reviewsCount: 12100,
    distance: '5.6 km',
    address: 'Mecidiye Köprüsü Sk. No:1 D:1, 34347 Beşiktaş/Istanbul',
    lat: 41.0473,
    lng: 29.027,
    image: 'https://images.unsplash.com/photo-1541432901042-2d8bd64b4a9b?auto=format&fit=crop&w=800&q=80',
    openNow: true,
    openingHours: '05:30 - 21:30',
    facilities: ['Bosphorus Waterfront', 'Baroque Architecture', 'Scenic Prayer Hall'],
    hasWomensArea: true,
    hasWuduArea: true,
    hasWheelchairAccess: false,
    jumuaTime: '13:00',
  },

  // ISTANBUL HALAL RESTAURANTS
  {
    id: 'food-1',
    name: 'Şehzade Cağ Kebap',
    city: 'Istanbul',
    country: 'Türkiye',
    category: 'restaurant',
    cuisine: 'Traditional Ottoman Wood-fired Kebab',
    rating: 4.9,
    reviewsCount: 4200,
    distance: '850 m',
    address: 'Hoca Paşa, Ankara Cd. No:114 D:2, Sirkeci/Istanbul',
    lat: 41.0135,
    lng: 28.9772,
    image: 'https://images.unsplash.com/photo-1555939594-58d7cb561ad1?auto=format&fit=crop&w=800&q=80',
    openNow: true,
    openingHours: '11:00 - 22:00',
    halalStatus: 'verified',
    facilities: ['100% Halal Meat Certified', 'Alcohol-Free Environment', 'Family Seating', 'Takeaway'],
    priceRange: '€€',
    alcoholFree: true,
  },
  {
    id: 'food-2',
    name: 'Tarihi Sultanahmet Köftecisi',
    city: 'Istanbul',
    country: 'Türkiye',
    category: 'restaurant',
    cuisine: 'Authentic Turkish Meatballs & Piyaz',
    rating: 4.7,
    reviewsCount: 16700,
    distance: '350 m',
    address: 'Alemdar, Divan Yolu Cd. No:12, 34110 Fatih/Istanbul',
    lat: 41.0079,
    lng: 28.9778,
    image: 'https://images.unsplash.com/photo-1544025162-d76694265947?auto=format&fit=crop&w=800&q=80',
    openNow: true,
    openingHours: '10:30 - 23:00',
    halalStatus: 'verified',
    facilities: ['Since 1920', 'TSE Halal Meat', 'Alcohol-Free', 'High Chairs Available'],
    priceRange: '€€',
    alcoholFree: true,
  },
  {
    id: 'food-3',
    name: 'Hafiz Mustafa 1864 (Sirkeci)',
    city: 'Istanbul',
    country: 'Türkiye',
    category: 'restaurant',
    cuisine: 'Ottoman Sweets, Kunafa, Baklava & Turkish Tea',
    rating: 4.8,
    reviewsCount: 31200,
    distance: '1.1 km',
    address: 'Hobyar, Hamidiye Cd. No:84, 34112 Fatih/Istanbul',
    lat: 41.0152,
    lng: 28.9749,
    image: 'https://images.unsplash.com/photo-1587314168485-3236d6710814?auto=format&fit=crop&w=800&q=80',
    openNow: true,
    openingHours: 'Open 24/7',
    halalStatus: 'verified',
    facilities: ['Alcohol-Free Cafe', 'Prayer Room on 2nd Floor', 'Gift Packaging', 'Famous Kunafa'],
    priceRange: '€€',
    alcoholFree: true,
  },
  {
    id: 'food-4',
    name: 'Çiya Sofrası',
    city: 'Istanbul',
    country: 'Türkiye',
    category: 'restaurant',
    cuisine: 'Anatolian Heritage & Silk Road Recipes',
    rating: 4.7,
    reviewsCount: 7800,
    distance: '4.2 km (Kadıköy Ferry)',
    address: 'Caferağa, Güneşli Bahçe Sok No:43, Kadıköy/Istanbul',
    lat: 40.9898,
    lng: 29.0253,
    image: 'https://images.unsplash.com/photo-1540420773420-3366772f4999?auto=format&fit=crop&w=800&q=80',
    openNow: true,
    openingHours: '11:00 - 22:00',
    halalStatus: 'verified',
    facilities: ['Extensive Vegetarian Options', 'Halal Slaughtered Lamb & Beef', 'Outdoor Garden Seating'],
    priceRange: '€€',
    alcoholFree: true,
  },
  {
    id: 'food-5',
    name: 'Matbah Ottoman Palace Cuisine',
    city: 'Istanbul',
    country: 'Türkiye',
    category: 'restaurant',
    cuisine: 'Imperial Palace Dishes (15th-19th Century)',
    rating: 4.8,
    reviewsCount: 3100,
    distance: '500 m',
    address: 'Cankurtaran, Caferiye Sk. No:6 D:1, Fatih/Istanbul',
    lat: 41.0089,
    lng: 28.9815,
    image: 'https://images.unsplash.com/photo-1517248135467-4c7edcad34c4?auto=format&fit=crop&w=800&q=80',
    openNow: true,
    openingHours: '12:00 - 23:00',
    halalStatus: 'community',
    facilities: ['Fine Dining', 'Historic Recipes', 'Prayer Mat Provided Upon Request'],
    priceRange: '€€€',
    alcoholFree: false,
  },

  // ISTANBUL MUSLIM-FRIENDLY HOTELS
  {
    id: 'hotel-1',
    name: 'AJWA Sultanahmet (Halal Certified Luxury)',
    city: 'Istanbul',
    country: 'Türkiye',
    category: 'hotel',
    rating: 4.9,
    reviewsCount: 1950,
    distance: '750 m',
    address: 'Emin Sinan, Piyer Loti Cd. No:30, 34126 Fatih/Istanbul',
    lat: 41.0068,
    lng: 28.9712,
    image: 'https://images.unsplash.com/photo-1566073771259-6a8506099945?auto=format&fit=crop&w=800&q=80',
    openNow: true,
    facilities: [
      '100% Halal Food Only',
      'Completely Alcohol-Free',
      'Qibla Marker & Prayer Mat in Every Room',
      'Holy Qur\'an in Room',
      'Separate Hours Ladies Turkish Hammam',
      '5 Mins Walk to Blue Mosque',
    ],
    priceRange: '€€€€',
    qiblaAvailable: true,
    alcoholFree: true,
  },
  {
    id: 'hotel-2',
    name: 'Sirkeci Mansion Hotel',
    city: 'Istanbul',
    country: 'Türkiye',
    category: 'hotel',
    rating: 4.8,
    reviewsCount: 2800,
    distance: '1.2 km',
    address: 'Taya Hatun Sk. No:4, 34110 Sirkeci/Istanbul',
    lat: 41.0131,
    lng: 28.9785,
    image: 'https://images.unsplash.com/photo-1582719508461-905c673771fd?auto=format&fit=crop&w=800&q=80',
    openNow: true,
    facilities: [
      'Halal Breakfast Buffet',
      'Qibla Direction Available',
      'Staff Assists with Prayer Schedules',
      'Family Friendly Suites',
    ],
    priceRange: '€€€',
    qiblaAvailable: true,
    alcoholFree: false,
  },

  // ISTANBUL PRAYER ROOMS & HOSPITALS
  {
    id: 'prayer-1',
    name: 'Grand Bazaar Prayer Hall (Kapalıçarşı Mescidi)',
    city: 'Istanbul',
    country: 'Türkiye',
    category: 'prayer_room',
    rating: 4.7,
    reviewsCount: 940,
    distance: '900 m',
    address: 'Beyazıt, Kalpakçılar Cd., 34126 Fatih/Istanbul',
    lat: 41.0107,
    lng: 28.968,
    image: 'https://images.unsplash.com/photo-1542601906990-b4d3fb778b09?auto=format&fit=crop&w=800&q=80',
    openNow: true,
    openingHours: '08:30 - 19:00',
    facilities: ['Dedicated Mens and Womens Halls', 'Clean Wudu Basins', 'Shoe Racks', 'Air Conditioned'],
    hasWomensArea: true,
    hasWuduArea: true,
  },
  {
    id: 'hospital-1',
    name: 'Istanbul Florence Nightingale Hospital',
    city: 'Istanbul',
    country: 'Türkiye',
    category: 'hospital',
    rating: 4.8,
    reviewsCount: 3400,
    distance: '6.8 km',
    address: 'Abide-i Hürriyet Cd. No:164, Şişli/Istanbul',
    lat: 41.0662,
    lng: 28.9855,
    image: 'https://images.unsplash.com/photo-1586773860418-d37222d8fce3?auto=format&fit=crop&w=800&q=80',
    openNow: true,
    openingHours: '24/7 Emergency Ward',
    facilities: ['24/7 Multilingual Emergency', 'Trauma Unit', 'English & Arabic Translators', 'On-site Prayer Room'],
    phone: '+90 212 224 4950',
  },
];
