import { Place } from '../types';

export const INITIAL_PLACES: Place[] = [
  // MOSQUES
  {
    id: 'mosque-1',
    name: 'Sultanahmet Mosque (Blue Mosque)',
    category: 'mosque',
    rating: 4.9,
    reviewsCount: 18450,
    distance: '450 m',
    address: 'Sultan Ahmet, Atmeydanı Cd. No:7, 34122 Fatih/Istanbul',
    lat: 41.0054,
    lng: 28.9768,
    image: 'https://images.unsplash.com/photo-1541432901042-2d8bd64b4a9b?auto=format&fit=crop&w=800&q=80',
    openNow: true,
    openingHours: 'Open 24 Hours for Prayers',
    facilities: ['Wudu Area', "Women's Prayer Section", 'Wheelchair Access', 'Historic Courtyard', 'Adhan Audio'],
    hasWomensArea: true,
    hasWuduArea: true,
    hasWheelchairAccess: true,
    jumuaTime: '13:00 (Khutbah in Turkish & Arabic)',
  },
  {
    id: 'mosque-2',
    name: 'Hagia Sophia Grand Mosque (Ayasofya)',
    category: 'mosque',
    rating: 4.9,
    reviewsCount: 22890,
    distance: '650 m',
    address: 'Sultan Ahmet, Ayasofya Meydanı No:1, 34122 Fatih/Istanbul',
    lat: 41.0086,
    lng: 28.9802,
    image: 'https://images.unsplash.com/photo-1527838832700-5059252407fa?auto=format&fit=crop&w=800&q=80',
    openNow: true,
    openingHours: 'Open for all 5 daily prayers',
    facilities: ['Active Congregation', 'Extensive Carpeting', "Dedicated Women's Section", 'Security Check'],
    hasWomensArea: true,
    hasWuduArea: true,
    hasWheelchairAccess: true,
    jumuaTime: '13:00',
  },
  {
    id: 'mosque-3',
    name: 'Süleymaniye Mosque (Süleymaniye Camii)',
    category: 'mosque',
    rating: 4.9,
    reviewsCount: 14200,
    distance: '1.4 km',
    address: 'Süleymaniye, Prof. Sıddık Sami Onar Cd. No:1, 34116 Fatih/Istanbul',
    lat: 41.0163,
    lng: 28.964,
    image: 'https://images.unsplash.com/photo-1564507592333-c60657eea523?auto=format&fit=crop&w=800&q=80',
    openNow: true,
    openingHours: '05:00 - 22:00',
    facilities: ['Panoramic Golden Horn View', 'Ablution Fountains', "Women's Gallery", 'Peaceful Gardens'],
    hasWomensArea: true,
    hasWuduArea: true,
    hasWheelchairAccess: true,
    jumuaTime: '13:15',
  },
  {
    id: 'mosque-4',
    name: 'Fatih Mosque (Fatih Camii)',
    category: 'mosque',
    rating: 4.8,
    reviewsCount: 8900,
    distance: '2.8 km',
    address: 'Hattat Nafiz Cd. No:6, 34083 Fatih/Istanbul',
    lat: 41.0197,
    lng: 28.9499,
    image: 'https://images.unsplash.com/photo-1565552645632-d725f8bfc19a?auto=format&fit=crop&w=800&q=80',
    openNow: true,
    openingHours: 'Open 24/7 for Salah',
    facilities: ['Madrasa Complex', 'Deep Islamic History', 'Large Wudu Facilities', "Women's Upper Balcony"],
    hasWomensArea: true,
    hasWuduArea: true,
    hasWheelchairAccess: true,
    jumuaTime: '13:00',
  },
  {
    id: 'mosque-5',
    name: 'Ortaköy Mosque (Büyük Mecidiye Camii)',
    category: 'mosque',
    rating: 4.8,
    reviewsCount: 12100,
    distance: '5.6 km',
    address: 'Mecidiye Köprüsü Sk. No:1 D:1, 34347 Beşiktaş/Istanbul',
    lat: 41.0473,
    lng: 29.027,
    image: 'https://images.unsplash.com/photo-1541432901042-2d8bd64b4a9b?auto=format&fit=crop&w=800&q=80',
    openNow: true,
    openingHours: '05:30 - 21:30',
    facilities: ['Bosphorus Waterfront', 'Baroque Architecture', 'Scenic Prayer Hall'],
    hasWomensArea: true,
    hasWuduArea: true,
    hasWheelchairAccess: false,
    jumuaTime: '13:00',
  },

  // HALAL RESTAURANTS
  {
    id: 'food-1',
    name: 'Şehzade Cağ Kebap',
    category: 'restaurant',
    cuisine: 'Traditional Ottoman Wood-fired Kebab',
    rating: 4.9,
    reviewsCount: 4200,
    distance: '850 m',
    address: 'Hoca Paşa, Ankara Cd. No:114 D:2, Sirkeci/Istanbul',
    lat: 41.0135,
    lng: 28.9772,
    image: 'https://images.unsplash.com/photo-1555939594-58d7cb561ad1?auto=format&fit=crop&w=800&q=80',
    openNow: true,
    openingHours: '11:00 - 22:00',
    halalStatus: 'verified',
    facilities: ['100% Halal Meat Certified', 'Alcohol-Free Environment', 'Family Seating', 'Takeaway'],
    priceRange: '€€',
    alcoholFree: true,
  },
  {
    id: 'food-2',
    name: 'Tarihi Sultanahmet Köftecisi',
    category: 'restaurant',
    cuisine: 'Authentic Turkish Meatballs & Piyaz',
    rating: 4.7,
    reviewsCount: 16700,
    distance: '350 m',
    address: 'Alemdar, Divan Yolu Cd. No:12, 34110 Fatih/Istanbul',
    lat: 41.0079,
    lng: 28.9778,
    image: 'https://images.unsplash.com/photo-1544025162-d76694265947?auto=format&fit=crop&w=800&q=80',
    openNow: true,
    openingHours: '10:30 - 23:00',
    halalStatus: 'verified',
    facilities: ['Since 1920', 'TSE Halal Meat', 'Alcohol-Free', 'High Chairs Available'],
    priceRange: '€€',
    alcoholFree: true,
  },
  {
    id: 'food-3',
    name: 'Hafiz Mustafa 1864 (Sirkeci)',
    category: 'restaurant',
    cuisine: 'Ottoman Sweets, Kunafa, Baklava & Turkish Tea',
    rating: 4.8,
    reviewsCount: 31200,
    distance: '1.1 km',
    address: 'Hobyar, Hamidiye Cd. No:84, 34112 Fatih/Istanbul',
    lat: 41.0152,
    lng: 28.9749,
    image: 'https://images.unsplash.com/photo-1587314168485-3236d6710814?auto=format&fit=crop&w=800&q=80',
    openNow: true,
    openingHours: 'Open 24/7',
    halalStatus: 'verified',
    facilities: ['Alcohol-Free Cafe', 'Prayer Room on 2nd Floor', 'Gift Packaging', 'Famous Kunafa'],
    priceRange: '€€',
    alcoholFree: true,
  },
  {
    id: 'food-4',
    name: 'Çiya Sofrası',
    category: 'restaurant',
    cuisine: 'Anatolian Heritage & Silk Road Recipes',
    rating: 4.7,
    reviewsCount: 7800,
    distance: '4.2 km (Kadıköy Ferry)',
    address: 'Caferağa, Güneşli Bahçe Sok No:43, Kadıköy/Istanbul',
    lat: 40.9898,
    lng: 29.0253,
    image: 'https://images.unsplash.com/photo-1540420773420-3366772f4999?auto=format&fit=crop&w=800&q=80',
    openNow: true,
    openingHours: '11:00 - 22:00',
    halalStatus: 'verified',
    facilities: ['Extensive Vegetarian Options', 'Halal Slaughtered Lamb & Beef', 'Outdoor Garden Seating'],
    priceRange: '€€',
    alcoholFree: true,
  },
  {
    id: 'food-5',
    name: 'Matbah Ottoman Palace Cuisine',
    category: 'restaurant',
    cuisine: 'Imperial Palace Dishes (15th-19th Century)',
    rating: 4.8,
    reviewsCount: 3100,
    distance: '500 m',
    address: 'Cankurtaran, Caferiye Sk. No:6 D:1, Fatih/Istanbul',
    lat: 41.0089,
    lng: 28.9815,
    image: 'https://images.unsplash.com/photo-1517248135467-4c7edcad34c4?auto=format&fit=crop&w=800&q=80',
    openNow: true,
    openingHours: '12:00 - 23:00',
    halalStatus: 'community',
    facilities: ['Fine Dining', 'Historic Recipes', 'Prayer Mat Provided Upon Request'],
    priceRange: '€€€',
    alcoholFree: false,
  },

  // MUSLIM-FRIENDLY HOTELS
  {
    id: 'hotel-1',
    name: 'AJWA Sultanahmet (Halal Certified Luxury)',
    category: 'hotel',
    rating: 4.9,
    reviewsCount: 1950,
    distance: '750 m',
    address: 'Emin Sinan, Piyer Loti Cd. No:30, 34126 Fatih/Istanbul',
    lat: 41.0068,
    lng: 28.9712,
    image: 'https://images.unsplash.com/photo-1566073771259-6a8506099945?auto=format&fit=crop&w=800&q=80',
    openNow: true,
    facilities: [
      '100% Halal Food Only',
      'Completely Alcohol-Free',
      'Qibla Marker & Prayer Mat in Every Room',
      'Holy Qur\'an in Room',
      'Separate Hours Ladies Turkish Hammam',
      '5 Mins Walk to Blue Mosque',
    ],
    priceRange: '€€€€',
    qiblaAvailable: true,
    alcoholFree: true,
  },
  {
    id: 'hotel-2',
    name: 'Sirkeci Mansion Hotel',
    category: 'hotel',
    rating: 4.8,
    reviewsCount: 2800,
    distance: '1.2 km',
    address: 'Taya Hatun Sk. No:4, 34110 Sirkeci/Istanbul',
    lat: 41.0131,
    lng: 28.9785,
    image: 'https://images.unsplash.com/photo-1582719508461-905c673771fd?auto=format&fit=crop&w=800&q=80',
    openNow: true,
    facilities: [
      'Halal Breakfast Buffet',
      'Qibla Direction Available',
      'Staff Assists with Prayer Schedules',
      'Family Friendly Suites',
    ],
    priceRange: '€€€',
    qiblaAvailable: true,
    alcoholFree: false,
  },

  // PRAYER ROOMS / CENTERS
  {
    id: 'prayer-1',
    name: 'Grand Bazaar Prayer Hall (Kapalıçarşı Mescidi)',
    category: 'prayer_room',
    rating: 4.7,
    reviewsCount: 940,
    distance: '900 m',
    address: 'Beyazıt, Kalpakçılar Cd., 34126 Fatih/Istanbul',
    lat: 41.0107,
    lng: 28.968,
    image: 'https://images.unsplash.com/photo-1542601906990-b4d3fb778b09?auto=format&fit=crop&w=800&q=80',
    openNow: true,
    openingHours: '08:30 - 19:00',
    facilities: ['Dedicated Mens and Womens Halls', 'Clean Wudu Basins', 'Shoe Racks', 'Air Conditioned'],
    hasWomensArea: true,
    hasWuduArea: true,
  },

  // HOSPITALS
  {
    id: 'hospital-1',
    name: 'Istanbul Florence Nightingale Hospital',
    category: 'hospital',
    rating: 4.8,
    reviewsCount: 3400,
    distance: '6.8 km',
    address: 'Abide-i Hürriyet Cd. No:164, Şişli/Istanbul',
    lat: 41.0662,
    lng: 28.9855,
    image: 'https://images.unsplash.com/photo-1586773860418-d37222d8fce3?auto=format&fit=crop&w=800&q=80',
    openNow: true,
    openingHours: '24/7 Emergency Ward',
    facilities: ['24/7 Multilingual Emergency', 'Trauma Unit', 'English & Arabic Translators', 'On-site Prayer Room'],
    phone: '+90 212 224 4950',
  },
];
